import type { BiomarkerDefinition } from "../types";

const chol: BiomarkerDefinition["conversion"] = {
  type: "linear",
  conventionalUnit: "mg/dL",
  siUnit: "mmol/L",
  factorCo: 0.0259,
  factorSi: 38.61,
};

const tg: BiomarkerDefinition["conversion"] = {
  type: "linear",
  conventionalUnit: "mg/dL",
  siUnit: "mmol/L",
  factorCo: 0.0113,
  factorSi: 88.5,
};

const glucoseConv: BiomarkerDefinition["conversion"] = {
  type: "linear",
  conventionalUnit: "mg/dL",
  siUnit: "mmol/L",
  factorCo: 0.0555,
  factorSi: 18.02,
};

const creatConv: BiomarkerDefinition["conversion"] = {
  type: "linear",
  conventionalUnit: "mg/dL",
  siUnit: "µmol/L",
  factorCo: 88.4,
  factorSi: 0.0113,
};

const biliConv: BiomarkerDefinition["conversion"] = {
  type: "linear",
  conventionalUnit: "mg/dL",
  siUnit: "µmol/L",
  factorCo: 17.1,
  factorSi: 0.0585,
};

const proteinConv: BiomarkerDefinition["conversion"] = {
  type: "linear",
  conventionalUnit: "g/dL",
  siUnit: "g/L",
  factorCo: 10,
  factorSi: 0.1,
};

const enzymeNone: BiomarkerDefinition["conversion"] = {
  type: "none",
  reason: "Enzyme activity units (U/L); no US/SI mass conversion",
};

const monoEqual = (a: string, b: string): BiomarkerDefinition["conversion"] => ({
  type: "equal",
  conventionalUnit: a,
  siUnit: b,
});

export const BIOMARKER_DEFINITIONS: BiomarkerDefinition[] = [
  // ── Cardiovascular ──────────────────────────────────────────────
  {
    key: "total_cholesterol",
    displayName: "Total cholesterol",
    system: "cardiovascular",
    scoreRole: "core",
    coversConfidence: true,
    aliases: [
      "total_cholesterol",
      "cholesterol_total",
      "tc",
      "chol",
      "общий_холестерин",
      "холестерин_общий",
      "охс",
    ],
    conversion: chol,
    tags: ["lipids"],
  },
  {
    key: "ldl",
    displayName: "LDL cholesterol",
    system: "cardiovascular",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["ldl", "ldl_c", "ldl_cholesterol", "лпнп", "хс_лпнп"],
    conversion: chol,
    tags: ["lipids"],
  },
  {
    key: "hdl",
    displayName: "HDL cholesterol",
    system: "cardiovascular",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["hdl", "hdl_c", "hdl_cholesterol", "лпвп", "хс_лпвп"],
    conversion: chol,
    tags: ["lipids"],
  },
  {
    key: "triglycerides",
    displayName: "Triglycerides",
    system: "cardiovascular",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["triglycerides", "tg", "trig", "триглицериды", "тг"],
    conversion: tg,
    tags: ["lipids"],
  },
  {
    key: "non_hdl_cholesterol",
    displayName: "Non-HDL cholesterol",
    system: "cardiovascular",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["non_hdl", "non_hdl_c", "non_hdl_cholesterol", "холестерин_не_лпвп", "не_лпвп"],
    conversion: chol,
    derived: true,
    tags: ["lipids"],
  },
  {
    key: "apob",
    displayName: "Apolipoprotein B",
    system: "cardiovascular",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["apob", "apo_b", "apolipoprotein_b", "апоb", "аполипопротеин_b", "апо_в"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "g/L",
      factorCo: 0.01,
      factorSi: 100,
    },
    tags: ["lipids"],
  },
  {
    key: "lpa",
    displayName: "Lipoprotein(a)",
    system: "cardiovascular",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["lpa", "lp_a", "lipoprotein_a", "lipoprotein_a_", "лп_а", "липопротеин_а", "лпа"],
    conversion: { type: "none", reason: "Lp(a) mg/dL↔nmol/L not safe with fixed factor" },
    tags: ["lipids", "cardiovascular_risk_marker"],
  },
  {
    key: "vldl",
    displayName: "VLDL cholesterol",
    system: "cardiovascular",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["vldl", "vldl_c", "vldl_cholesterol"],
    conversion: chol,
    tags: ["lipids"],
  },
  {
    key: "remnant_cholesterol",
    displayName: "Remnant cholesterol",
    system: "cardiovascular",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["remnant_cholesterol", "remnant_c"],
    conversion: chol,
    derived: true,
    tags: ["lipids"],
  },

  // ── Metabolic ───────────────────────────────────────────────────
  {
    key: "glucose",
    displayName: "Glucose",
    system: "metabolic",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["glucose", "blood_glucose", "blood_sugar", "random_glucose", "глюкоза", "сахар_крови"],
    conversion: glucoseConv,
    tags: ["cmp", "metabolic"],
  },
  {
    key: "fasting_glucose",
    displayName: "Fasting glucose",
    system: "metabolic",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["fasting_glucose", "fpg", "fasting_plasma_glucose", "глюкоза_натощак"],
    conversion: glucoseConv,
    tags: ["metabolic"],
  },
  {
    key: "hba1c",
    displayName: "Hemoglobin A1c",
    system: "metabolic",
    scoreRole: "core",
    coversConfidence: true,
    aliases: [
      "hba1c",
      "a1c",
      "hb_a1c",
      "glycated_hemoglobin",
      "glycohemoglobin",
      "hemoglobin_a1c",
      "гликированный_гемоглобин",
      "гликогемоглобин",
    ],
    conversion: {
      type: "formula",
      formula: "hba1c_ngsp_ifcc",
      conventionalUnit: "%",
      siUnit: "mmol/mol",
    },
    tags: ["metabolic"],
  },
  {
    key: "insulin",
    displayName: "Insulin",
    system: "metabolic",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["insulin", "инсулин"],
    conversion: monoEqual("µIU/mL", "mIU/L"),
    tags: ["metabolic"],
  },
  {
    key: "c_peptide",
    displayName: "C-peptide",
    system: "metabolic",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["c_peptide", "cpeptide", "с_пептид", "c_пептид"],
    conversion: {
      type: "linear",
      conventionalUnit: "ng/mL",
      siUnit: "nmol/L",
      factorCo: 0.33,
      factorSi: 3.03,
    },
  },

  // ── Thyroid ─────────────────────────────────────────────────────
  {
    key: "tsh",
    displayName: "TSH",
    system: "thyroid",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["tsh", "thyrotropin", "ттг", "тиреотропный_гормон"],
    conversion: monoEqual("µIU/mL", "mIU/L"),
  },
  {
    key: "free_t4",
    displayName: "Free T4",
    system: "thyroid",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["free_t4", "ft4", "free_thyroxine", "свободный_т4", "св_т4", "т4_свободный"],
    conversion: {
      type: "linear",
      conventionalUnit: "ng/dL",
      siUnit: "pmol/L",
      factorCo: 12.9,
      factorSi: 0.0775,
    },
  },
  {
    key: "free_t3",
    displayName: "Free T3",
    system: "thyroid",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["free_t3", "ft3", "свободный_т3", "св_т3"],
    conversion: {
      type: "linear",
      conventionalUnit: "pg/mL",
      siUnit: "pmol/L",
      factorCo: 1.536,
      factorSi: 0.651,
    },
  },
  {
    key: "t3",
    displayName: "Total T3",
    system: "thyroid",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["t3", "total_t3", "triiodothyronine", "т3", "т3_общий"],
    conversion: {
      type: "linear",
      conventionalUnit: "ng/dL",
      siUnit: "nmol/L",
      factorCo: 0.0154,
      factorSi: 64.9,
    },
  },
  {
    key: "t4",
    displayName: "Total T4",
    system: "thyroid",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["t4", "total_t4", "thyroxine", "т4", "т4_общий"],
    conversion: {
      type: "linear",
      conventionalUnit: "µg/dL",
      siUnit: "nmol/L",
      factorCo: 12.9,
      factorSi: 0.0775,
    },
  },
  {
    key: "anti_tpo",
    displayName: "Anti-TPO",
    system: "thyroid",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["anti_tpo", "tpo_ab", "tpo_antibodies", "ат_тпо", "антитела_к_тпо"],
    conversion: { type: "none", reason: "Assay-specific antibody units" },
  },
  {
    key: "anti_tg",
    displayName: "Anti-Tg",
    system: "thyroid",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["anti_tg", "tgab", "tg_ab", "ат_тг", "антитела_к_тг"],
    conversion: { type: "none", reason: "Assay-specific antibody units" },
  },
  {
    key: "trab",
    displayName: "TSH receptor antibodies",
    system: "thyroid",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["trab", "tsh_receptor_antibodies", "tbii", "ат_к_рецепторам_ттг"],
    conversion: { type: "none", reason: "Assay-specific antibody units" },
  },

  // ── Liver ───────────────────────────────────────────────────────
  {
    key: "alt",
    displayName: "ALT",
    system: "liver",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["alt", "sgpt", "alanine_aminotransferase", "алт", "алат"],
    conversion: enzymeNone,
  },
  {
    key: "ast",
    displayName: "AST",
    system: "liver",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["ast", "sgot", "aspartate_aminotransferase", "аст", "асат"],
    conversion: enzymeNone,
  },
  {
    key: "alp",
    displayName: "Alkaline phosphatase",
    system: "liver",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["alp", "alkaline_phosphatase", "щф", "щелочная_фосфатаза"],
    conversion: enzymeNone,
  },
  {
    key: "ggt",
    displayName: "GGT",
    system: "liver",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["ggt", "gamma_gt", "gamma_glutamyl_transferase", "ггт"],
    conversion: enzymeNone,
  },
  {
    key: "bilirubin",
    displayName: "Total bilirubin",
    system: "liver",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["bilirubin", "total_bilirubin", "bili_total", "билирубин", "билирубин_общий"],
    conversion: biliConv,
  },
  {
    key: "albumin",
    displayName: "Albumin",
    system: "liver",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["albumin", "альбумин"],
    conversion: proteinConv,
    tags: ["cmp", "proteins"],
  },
  {
    key: "direct_bilirubin",
    displayName: "Direct bilirubin",
    system: "liver",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["direct_bilirubin", "conjugated_bilirubin", "билирубин_прямой"],
    conversion: biliConv,
  },
  {
    key: "indirect_bilirubin",
    displayName: "Indirect bilirubin",
    system: "liver",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["indirect_bilirubin", "unconjugated_bilirubin", "билирубин_непрямой"],
    conversion: biliConv,
  },
  {
    key: "total_protein",
    displayName: "Total protein",
    system: "liver",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["total_protein", "общий_белок"],
    conversion: proteinConv,
    tags: ["cmp", "proteins"],
  },
  {
    key: "globulin",
    displayName: "Globulin",
    system: "liver",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["globulin", "глобулин"],
    conversion: proteinConv,
    tags: ["proteins"],
  },

  // ── Kidney / electrolytes / urine quant ─────────────────────────
  {
    key: "creatinine",
    displayName: "Creatinine",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["creatinine", "creat", "креатинин"],
    conversion: creatConv,
    specimen: "serum",
    tags: ["cmp", "kidney"],
  },
  {
    key: "egfr",
    displayName: "eGFR",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["egfr", "estimated_gfr", "egfrcr", "ckd_epi", "скф", "рскф"],
    conversion: { type: "none", reason: "eGFR already mL/min/1.73 m²" },
    tags: ["kidney"],
  },
  {
    key: "bun",
    displayName: "BUN",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["bun", "blood_urea_nitrogen", "urea_nitrogen", "азот_мочевины"],
    conversion: {
      type: "formula",
      formula: "bun_urea",
      conventionalUnit: "mg/dL",
      siUnit: "mmol/L",
    },
    equivalenceGroup: "urea_nitrogen",
    tags: ["cmp", "kidney"],
  },
  {
    key: "urea",
    displayName: "Urea",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["urea", "мочевина"],
    conversion: {
      type: "formula",
      formula: "bun_urea",
      conventionalUnit: "mg/dL",
      siUnit: "mmol/L",
    },
    equivalenceGroup: "urea_nitrogen",
    tags: ["kidney"],
  },
  {
    key: "sodium",
    displayName: "Sodium",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: false,
    aliases: ["sodium", "натрий"],
    // Note: bare "na" is handled carefully in normalize (not n_a)
    conversion: monoEqual("mEq/L", "mmol/L"),
    tags: ["electrolytes", "cmp"],
  },
  {
    key: "potassium",
    displayName: "Potassium",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: false,
    aliases: ["potassium", "калий"],
    conversion: monoEqual("mEq/L", "mmol/L"),
    tags: ["electrolytes", "cmp"],
  },
  {
    key: "chloride",
    displayName: "Chloride",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: false,
    aliases: ["chloride", "хлор", "хлориды"],
    conversion: monoEqual("mEq/L", "mmol/L"),
    tags: ["electrolytes", "cmp"],
  },
  {
    key: "bicarbonate",
    displayName: "Bicarbonate / CO2",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: false,
    aliases: [
      "bicarbonate",
      "co2",
      "carbon_dioxide",
      "total_co2",
      "hco3",
      "бикарбонат",
      "гидрокарбонат",
    ],
    conversion: monoEqual("mEq/L", "mmol/L"),
    tags: ["electrolytes", "cmp"],
  },
  {
    key: "calcium",
    displayName: "Calcium",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: false,
    aliases: ["calcium", "кальций"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "mmol/L",
      factorCo: 0.25,
      factorSi: 4,
    },
    tags: ["electrolytes", "cmp"],
  },
  {
    key: "uacr",
    displayName: "Urine albumin/creatinine ratio",
    system: "kidney",
    scoreRole: "core",
    coversConfidence: true,
    aliases: [
      "uacr",
      "acr",
      "albumin_creatinine_ratio",
      "microalbumin_creatinine_ratio",
      "альбумин_креатинин",
      "акр",
    ],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/g",
      siUnit: "mg/mmol",
      factorCo: 0.113,
      factorSi: 8.84,
    },
    specimen: "urine",
    tags: ["urine", "kidney"],
  },
  {
    key: "magnesium",
    displayName: "Magnesium",
    system: "kidney",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["magnesium", "магний"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "mmol/L",
      factorCo: 0.4114,
      factorSi: 2.43,
    },
    tags: ["electrolytes"],
  },
  {
    key: "phosphate",
    displayName: "Phosphate",
    system: "kidney",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["phosphate", "phosphorus", "po4", "фосфор", "фосфат"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "mmol/L",
      factorCo: 0.323,
      factorSi: 3.1,
    },
    tags: ["electrolytes"],
  },
  {
    key: "uric_acid",
    displayName: "Uric acid",
    system: "kidney",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["uric_acid", "urate", "мочевая_кислота"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "µmol/L",
      factorCo: 59,
      factorSi: 0.0169,
    },
  },
  {
    key: "urine_albumin",
    displayName: "Urine albumin",
    system: "kidney",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["urine_albumin", "microalbumin", "альбумин_в_моче", "микроальбумин"],
    specimen: "urine",
    tags: ["urine"],
  },
  {
    key: "urine_creatinine",
    displayName: "Urine creatinine",
    system: "kidney",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["urine_creatinine", "креатинин_в_моче"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "mmol/L",
      factorCo: 0.0884,
      factorSi: 11.31,
    },
    specimen: "urine",
    tags: ["urine"],
  },
  {
    key: "urine_protein",
    displayName: "Urine protein",
    system: "kidney",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["urine_protein", "белок_в_моче"],
    specimen: "urine",
    tags: ["urine"],
  },

  // ── Blood / CBC / iron ──────────────────────────────────────────
  {
    key: "hemoglobin",
    displayName: "Hemoglobin",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["hemoglobin", "hb", "hgb", "гемоглобин"],
    conversion: {
      type: "linear",
      conventionalUnit: "g/dL",
      siUnit: "g/L",
      factorCo: 10,
      factorSi: 0.1,
    },
    tags: ["cbc"],
  },
  {
    key: "hematocrit",
    displayName: "Hematocrit",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["hematocrit", "hct", "pcv", "гематокрит"],
    conversion: {
      type: "linear",
      conventionalUnit: "%",
      siUnit: "L/L",
      factorCo: 0.01,
      factorSi: 100,
    },
    tags: ["cbc"],
  },
  {
    key: "rbc",
    displayName: "RBC",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["rbc", "red_blood_cells", "erythrocytes", "эритроциты"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc"],
  },
  {
    key: "wbc",
    displayName: "WBC",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["wbc", "white_blood_cells", "leukocytes", "лейкоциты"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc"],
  },
  {
    key: "platelets",
    displayName: "Platelets",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["platelets", "plt", "thrombocytes", "тромбоциты"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc"],
  },
  {
    key: "mcv",
    displayName: "MCV",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["mcv", "mean_corpuscular_volume"],
    conversion: { type: "none", reason: "Already fL" },
    tags: ["cbc"],
  },
  {
    key: "rdw",
    displayName: "RDW",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["rdw", "red_cell_distribution_width"],
    conversion: { type: "none", reason: "Percent / ratio" },
    tags: ["cbc"],
  },
  {
    key: "ferritin",
    displayName: "Ferritin",
    system: "blood",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["ferritin", "ферритин"],
    conversion: monoEqual("ng/mL", "µg/L"),
    tags: ["iron_studies"],
  },
  {
    key: "mch",
    displayName: "MCH",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["mch"],
    conversion: { type: "none", reason: "Already pg" },
    tags: ["cbc"],
  },
  {
    key: "mchc",
    displayName: "MCHC",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["mchc"],
    conversion: {
      type: "linear",
      conventionalUnit: "g/dL",
      siUnit: "g/L",
      factorCo: 10,
      factorSi: 0.1,
    },
    tags: ["cbc"],
  },
  {
    key: "neutrophils",
    displayName: "Neutrophils (absolute)",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["neutrophils", "neutrophils_abs", "anc", "absolute_neutrophil_count", "нейтрофилы"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc", "differential"],
  },
  {
    key: "lymphocytes",
    displayName: "Lymphocytes (absolute)",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["lymphocytes", "lymphocytes_abs", "лимфоциты"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc", "differential"],
  },
  {
    key: "monocytes",
    displayName: "Monocytes (absolute)",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["monocytes", "monocytes_abs", "моноциты"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc", "differential"],
  },
  {
    key: "eosinophils",
    displayName: "Eosinophils (absolute)",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["eosinophils", "eosinophils_abs", "эозинофилы"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc", "differential"],
  },
  {
    key: "basophils",
    displayName: "Basophils (absolute)",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["basophils", "basophils_abs", "базофилы"],
    conversion: monoEqual("×10³/µL", "×10⁹/L"),
    tags: ["cbc", "differential"],
  },
  {
    key: "neutrophils_percent",
    displayName: "Neutrophils %",
    system: "blood",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["neutrophils_percent", "neutrophils_", "нейтрофилы_"],
    conversion: { type: "none", reason: "Percent" },
    tags: ["cbc", "differential"],
  },
  {
    key: "lymphocytes_percent",
    displayName: "Lymphocytes %",
    system: "blood",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["lymphocytes_percent", "лимфоциты_"],
    conversion: { type: "none", reason: "Percent" },
    tags: ["cbc", "differential"],
  },
  {
    key: "monocytes_percent",
    displayName: "Monocytes %",
    system: "blood",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["monocytes_percent", "моноциты_"],
    conversion: { type: "none", reason: "Percent" },
    tags: ["cbc", "differential"],
  },
  {
    key: "eosinophils_percent",
    displayName: "Eosinophils %",
    system: "blood",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["eosinophils_percent", "эозинофилы_"],
    conversion: { type: "none", reason: "Percent" },
    tags: ["cbc", "differential"],
  },
  {
    key: "basophils_percent",
    displayName: "Basophils %",
    system: "blood",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["basophils_percent", "базофилы_"],
    conversion: { type: "none", reason: "Percent" },
    tags: ["cbc", "differential"],
  },
  {
    key: "iron",
    displayName: "Serum iron",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["iron", "serum_iron", "fe", "сывороточное_железо", "железо"],
    conversion: {
      type: "linear",
      conventionalUnit: "µg/dL",
      siUnit: "µmol/L",
      factorCo: 0.179,
      factorSi: 5.587,
    },
    tags: ["iron_studies"],
  },
  {
    key: "tibc",
    displayName: "TIBC",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["tibc", "total_iron_binding_capacity", "ожсс"],
    conversion: {
      type: "linear",
      conventionalUnit: "µg/dL",
      siUnit: "µmol/L",
      factorCo: 0.179,
      factorSi: 5.587,
    },
    tags: ["iron_studies"],
  },
  {
    key: "uibc",
    displayName: "UIBC",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["uibc", "unsaturated_iron_binding_capacity", "нжсс", "лжсс"],
    conversion: {
      type: "linear",
      conventionalUnit: "µg/dL",
      siUnit: "µmol/L",
      factorCo: 0.179,
      factorSi: 5.587,
    },
    tags: ["iron_studies"],
  },
  {
    key: "transferrin",
    displayName: "Transferrin",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["transferrin", "трансферрин"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "g/L",
      factorCo: 0.01,
      factorSi: 100,
    },
    tags: ["iron_studies"],
  },
  {
    key: "transferrin_saturation",
    displayName: "Transferrin saturation",
    system: "blood",
    scoreRole: "extended",
    coversConfidence: false,
    aliases: ["transferrin_saturation", "tsat", "t_sat", "насыщение_трансферрина"],
    conversion: { type: "none", reason: "Percent" },
    tags: ["iron_studies"],
  },

  // ── Nutrients ───────────────────────────────────────────────────
  {
    key: "vitamin_d",
    displayName: "Vitamin D (25-OH)",
    system: "nutrients",
    scoreRole: "core",
    coversConfidence: true,
    aliases: [
      "vitamin_d",
      "25_oh_vitamin_d",
      "25_hydroxyvitamin_d",
      "25_oh_d",
      "25_ohd",
      "calcidiol",
      "витамин_d",
      "25_он_витамин_d",
    ],
    conversion: {
      type: "linear",
      conventionalUnit: "ng/mL",
      siUnit: "nmol/L",
      factorCo: 2.5,
      factorSi: 0.4,
    },
  },
  {
    key: "b12",
    displayName: "Vitamin B12",
    system: "nutrients",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["b12", "vitamin_b12", "cobalamin", "витамин_b12", "кобаламин"],
    conversion: {
      type: "linear",
      conventionalUnit: "pg/mL",
      siUnit: "pmol/L",
      factorCo: 0.738,
      factorSi: 1.355,
    },
  },
  {
    key: "folate",
    displayName: "Folate",
    system: "nutrients",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["folate", "folic_acid", "vitamin_b9", "фолат", "фолиевая_кислота"],
    conversion: {
      type: "linear",
      conventionalUnit: "ng/mL",
      siUnit: "nmol/L",
      factorCo: 2.265,
      factorSi: 0.442,
    },
  },

  // ── Inflammation ────────────────────────────────────────────────
  {
    key: "crp",
    displayName: "CRP",
    system: "inflammation",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["crp", "c_reactive_protein", "срб", "c_реактивный_белок"],
    conversion: {
      type: "linear",
      conventionalUnit: "mg/dL",
      siUnit: "mg/L",
      factorCo: 10,
      factorSi: 0.1,
    },
    tags: ["inflammation"],
  },
  {
    key: "hs_crp",
    displayName: "hs-CRP",
    system: "inflammation",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["hs_crp", "high_sensitivity_crp", "cardiac_crp", "вч_срб", "hscrp"],
    conversion: { type: "none", reason: "Usually already mg/L" },
    tags: ["inflammation", "cardiovascular_risk_marker"],
  },
  {
    key: "esr",
    displayName: "ESR",
    system: "inflammation",
    scoreRole: "core",
    coversConfidence: true,
    aliases: ["esr", "sedimentation_rate", "erythrocyte_sedimentation_rate", "соэ"],
    conversion: { type: "none", reason: "mm/hr" },
    tags: ["inflammation"],
  },

  // ── Display-only specialty stubs ────────────────────────────────
  {
    key: "psa",
    displayName: "PSA",
    system: "general",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["psa", "prostate_specific_antigen", "пса"],
  },
  {
    key: "d_dimer",
    displayName: "D-dimer",
    system: "general",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["d_dimer", "d_димер", "д_димер"],
  },
  {
    key: "inr",
    displayName: "INR",
    system: "general",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["inr", "мно"],
  },
  {
    key: "pt",
    displayName: "Prothrombin time",
    system: "general",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["pt", "prothrombin_time", "пв"],
  },
  {
    key: "aptt",
    displayName: "aPTT",
    system: "general",
    scoreRole: "display",
    coversConfidence: false,
    aliases: ["aptt", "ptt", "ачтв"],
  },
];
