import { resolveMeasurementDefinition } from "./measurement-resolution";
import type { MeasurementValueKind } from "./types";

export type LaunchResolverFixture = { id: string; rawLabel: string; rawUnit: string | null; valueKind: MeasurementValueKind; section: string };
const numeric = (id: string, rawLabel: string, rawUnit: string | null, section: string): LaunchResolverFixture => ({ id, rawLabel, rawUnit, valueKind: "numeric", section });
const qualitative = (id: string, rawLabel: string, rawUnit: string | null): LaunchResolverFixture => ({ id, rawLabel, rawUnit, valueKind: "qualitative", section: "Serology, parasitology, allergy markers" });

export const SAMPLE_NEWEST_LAUNCH_FIXTURES: readonly LaunchResolverFixture[] = [
  numeric("total-protein", "Total protein", "g/L", "Biochemistry and inflammation"), numeric("glucose", "Glucose", "mmol/L", "Biochemistry and inflammation"), numeric("total-bilirubin", "Total bilirubin", "umol/L", "Biochemistry and inflammation"), numeric("direct-bilirubin", "Direct bilirubin", "umol/L", "Biochemistry and inflammation"), numeric("alt", "ALT (alanine aminotransferase)", "U/L", "Biochemistry and inflammation"), numeric("ast", "AST (aspartate aminotransferase)", "U/L", "Biochemistry and inflammation"), numeric("crp", "C-reactive protein, quantitative", "mg/L", "Biochemistry and inflammation"), numeric("aso", "Antistreptolysin-O (ASO)", "IU/mL", "Biochemistry and inflammation"),
  numeric("rbc", "Red blood cells (RBC)", "x10^12/L", "CBC"), numeric("hgb", "Hemoglobin (HGB)", "g/L", "CBC"), numeric("hct", "Hematocrit (HCT)", "%", "CBC"), numeric("mcv", "Mean corpuscular volume (MCV)", "fL", "CBC"), numeric("mch", "Mean corpuscular hemoglobin (MCH)", "pg", "CBC"), numeric("mchc", "Mean corpuscular hemoglobin concentration (MCHC)", "g/L", "CBC"), numeric("rdw", "Red cell distribution width (RDW)", "%", "CBC"), numeric("plt", "Platelets (PLT)", "x10^9/L", "CBC"), numeric("mpv", "Mean platelet volume (MPV)", "fL", "CBC"), numeric("pdw", "Platelet distribution width (PDW)", "%", "CBC"), numeric("pct", "Plateletcrit (PCT)", "%", "CBC"), numeric("wbc", "White blood cells (WBC)", "x10^9/L", "CBC"), numeric("neu-percent", "Neutrophils (NEU%)", "%", "CBC"), numeric("neu-abs", "Neutrophils, absolute (NEU)", "x10^9/L", "CBC"), numeric("lymf-percent", "Lymphocytes (LYMF%)", "%", "CBC"), numeric("lymf-abs", "Lymphocytes, absolute (LYMF)", "x10^9/L", "CBC"), numeric("mon-percent", "Monocytes (MON%)", "%", "CBC"), numeric("mon-abs", "Monocytes, absolute (MON)", "x10^9/L", "CBC"), numeric("eos-percent", "Eosinophils (EOS%)", "%", "CBC"), numeric("eos-abs", "Eosinophils, absolute (EOS)", "x10^9/L", "CBC"), numeric("bas-percent", "Basophils (BAS%)", "%", "CBC"), numeric("bas-abs", "Basophils, absolute (BAS)", "x10^9/L", "CBC"), numeric("esr", "ESR, Westergren automated", "mm/hour", "CBC"), numeric("segmented", "Segmented neutrophils", "%", "CBC"), numeric("band", "Band neutrophils", "%", "CBC"), numeric("lymph-manual", "Lymphocytes, manual differential", "%", "CBC"), numeric("mon-manual", "Monocytes, manual differential", "%", "CBC"), numeric("eos-manual", "Eosinophils, manual differential", "%", "CBC"),
  numeric("giardia", "Giardia antibodies, total", "positivity coefficient", "Serology, parasitology, allergy markers"), qualitative("ascaris", "Ascaris IgG antibodies", "titer"), qualitative("toxocara", "anti-Toxocara IgG, qualitative ELISA", null), qualitative("opisthorchis", "anti-Opisthorchis felineus IgG, qualitative ELISA", null), qualitative("echinococcus", "anti-Echinococcus IgG, qualitative ELISA", null), qualitative("trichinella", "anti-Trichinella sp. IgG, qualitative ELISA", null), numeric("total-ige", "Total IgE", "IU/mL", "Serology, parasitology, allergy markers"), numeric("ecp", "Eosinophilic cationic protein (ECP)", "ng/mL", "Serology, parasitology, allergy markers"),
];

export function buildLaunchCoverageReport(fixtures = SAMPLE_NEWEST_LAUNCH_FIXTURES) {
  const rows = fixtures.map((fixture) => ({ fixture, resolution: resolveMeasurementDefinition(fixture) }));
  const count = (predicate: (row: (typeof rows)[number]) => boolean) => rows.filter(predicate).length;
  return {
    total: rows.length,
    recognized: count((row) => row.resolution.result !== "unmapped"), resolved: count((row) => row.resolution.result === "resolved"), ambiguous: count((row) => row.resolution.result === "ambiguous"), partial: count((row) => row.resolution.result === "partial"), unmapped: count((row) => row.resolution.result === "unmapped"), unitCompatible: count((row) => !row.resolution.conflicts.some((conflict) => conflict.startsWith("unit_"))), valueKindDeclared: count((row) => row.fixture.valueKind !== "unspecified"), assessmentEligible: count((row) => row.resolution.result === "resolved"), rows,
  };
}
