// Generated by scripts/generate-launch-catalog.ts from the frozen Registry v1 audit fixture.
// Do not edit by hand; application runtime imports this materialized launch catalog, never Registry v1.
import type { LaunchCatalogMigrationRecord } from "./types";

export const LAUNCH_CATALOG_MIGRATION_RECORDS: readonly LaunchCatalogMigrationRecord[] = [
  {
    "key": "migration_afp",
    "analyteKey": "afp",
    "displayName": "AFP",
    "aliases": [
      "afp",
      "alpha_fetoprotein"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "afp"
  },
  {
    "key": "migration_albumin",
    "analyteKey": "albumin",
    "displayName": "Albumin",
    "aliases": [
      "albumin",
      "альбумин"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "g/dL",
      "factorCo": 10,
      "factorSi": 0.1,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "albumin"
  },
  {
    "key": "migration_alp",
    "analyteKey": "alp",
    "displayName": "Alkaline phosphatase",
    "aliases": [
      "alkaline_phosphatase",
      "alp",
      "щелочная_фосфатаза",
      "щф"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "core",
    "conversion": {
      "reason": "Enzyme activity units (U/L); no US/SI mass conversion",
      "type": "none"
    },
    "sourceRecordKey": "alp"
  },
  {
    "key": "migration_alt",
    "analyteKey": "alt",
    "displayName": "ALT",
    "aliases": [
      "alanine_aminotransferase",
      "alt",
      "sgpt",
      "алат",
      "алт"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "core",
    "conversion": {
      "reason": "Enzyme activity units (U/L); no US/SI mass conversion",
      "type": "none"
    },
    "sourceRecordKey": "alt"
  },
  {
    "key": "migration_ana",
    "analyteKey": "ana",
    "displayName": "ANA",
    "aliases": [
      "ana",
      "antinuclear_antibodies",
      "анф"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "ana"
  },
  {
    "key": "migration_anti_tg",
    "analyteKey": "anti_tg",
    "displayName": "Anti-Tg",
    "aliases": [
      "anti_tg",
      "tg_ab",
      "tgab",
      "антитела_к_тг",
      "ат_тг"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "extended",
    "conversion": {
      "reason": "Assay-specific antibody units",
      "type": "none"
    },
    "sourceRecordKey": "anti_tg"
  },
  {
    "key": "migration_anti_tpo",
    "analyteKey": "anti_tpo",
    "displayName": "Anti-TPO",
    "aliases": [
      "anti_tpo",
      "tpo_ab",
      "tpo_antibodies",
      "антитела_к_тпо",
      "ат_тпо"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "extended",
    "conversion": {
      "reason": "Assay-specific antibody units",
      "type": "none"
    },
    "sourceRecordKey": "anti_tpo"
  },
  {
    "key": "migration_apob",
    "analyteKey": "apob",
    "displayName": "Apolipoprotein B",
    "aliases": [
      "apo_b",
      "apob",
      "apolipoprotein_b",
      "апо_в",
      "апоb",
      "аполипопротеин_b"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.01,
      "factorSi": 100,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "apob"
  },
  {
    "key": "migration_aptt",
    "analyteKey": "aptt",
    "displayName": "aPTT",
    "aliases": [
      "aptt",
      "ptt",
      "ачтв"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "aptt"
  },
  {
    "key": "migration_ast",
    "analyteKey": "ast",
    "displayName": "AST",
    "aliases": [
      "aspartate_aminotransferase",
      "ast",
      "sgot",
      "асат",
      "аст"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "core",
    "conversion": {
      "reason": "Enzyme activity units (U/L); no US/SI mass conversion",
      "type": "none"
    },
    "sourceRecordKey": "ast"
  },
  {
    "key": "migration_b12",
    "analyteKey": "b12",
    "displayName": "Vitamin B12",
    "aliases": [
      "b12",
      "cobalamin",
      "vitamin_b12",
      "витамин_b12",
      "кобаламин"
    ],
    "specimen": "unspecified",
    "system": "nutrients",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "pg/mL",
      "factorCo": 0.738,
      "factorSi": 1.355,
      "siUnit": "pmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "b12"
  },
  {
    "key": "migration_basophils",
    "analyteKey": "basophils",
    "displayName": "Basophils (absolute)",
    "aliases": [
      "basophils",
      "basophils_abs",
      "базофилы"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "basophils"
  },
  {
    "key": "migration_basophils_percent",
    "analyteKey": "basophils_percent",
    "displayName": "Basophils %",
    "aliases": [
      "basophils_percent",
      "базофилы_"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "display",
    "conversion": {
      "reason": "Percent",
      "type": "none"
    },
    "sourceRecordKey": "basophils_percent"
  },
  {
    "key": "migration_bicarbonate",
    "analyteKey": "bicarbonate",
    "displayName": "Bicarbonate / CO2",
    "aliases": [
      "bicarbonate",
      "carbon_dioxide",
      "co2",
      "hco3",
      "total_co2",
      "бикарбонат",
      "гидрокарбонат"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mEq/L",
      "siUnit": "mmol/L",
      "type": "equal"
    },
    "sourceRecordKey": "bicarbonate"
  },
  {
    "key": "migration_bilirubin",
    "analyteKey": "bilirubin",
    "displayName": "Total bilirubin",
    "aliases": [
      "bili_total",
      "bilirubin",
      "total_bilirubin",
      "билирубин",
      "билирубин_общий"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 17.1,
      "factorSi": 0.0585,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "bilirubin"
  },
  {
    "key": "migration_bnp",
    "analyteKey": "bnp",
    "displayName": "BNP",
    "aliases": [
      "bnp"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "bnp"
  },
  {
    "key": "migration_bun",
    "analyteKey": "bun",
    "displayName": "BUN",
    "aliases": [
      "blood_urea_nitrogen",
      "bun",
      "urea_nitrogen",
      "азот_мочевины"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "formula": "bun_urea",
      "siUnit": "mmol/L",
      "type": "formula"
    },
    "sourceRecordKey": "bun"
  },
  {
    "key": "migration_c_peptide",
    "analyteKey": "c_peptide",
    "displayName": "C-peptide",
    "aliases": [
      "c_peptide",
      "c_пептид",
      "cpeptide",
      "с_пептид"
    ],
    "specimen": "unspecified",
    "system": "metabolic",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "ng/mL",
      "factorCo": 0.33,
      "factorSi": 3.03,
      "siUnit": "nmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "c_peptide"
  },
  {
    "key": "migration_ca_125",
    "analyteKey": "ca_125",
    "displayName": "CA-125",
    "aliases": [
      "ca125",
      "ca_125"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "ca_125"
  },
  {
    "key": "migration_ca_19_9",
    "analyteKey": "ca_19_9",
    "displayName": "CA 19-9",
    "aliases": [
      "ca199",
      "ca_19_9"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "ca_19_9"
  },
  {
    "key": "migration_calcium",
    "analyteKey": "calcium",
    "displayName": "Calcium",
    "aliases": [
      "calcium",
      "кальций"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.25,
      "factorSi": 4,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "calcium"
  },
  {
    "key": "migration_cea",
    "analyteKey": "cea",
    "displayName": "CEA",
    "aliases": [
      "carcinoembryonic_antigen",
      "cea"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "cea"
  },
  {
    "key": "migration_chloride",
    "analyteKey": "chloride",
    "displayName": "Chloride",
    "aliases": [
      "chloride",
      "хлор",
      "хлориды"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mEq/L",
      "siUnit": "mmol/L",
      "type": "equal"
    },
    "sourceRecordKey": "chloride"
  },
  {
    "key": "migration_cortisol",
    "analyteKey": "cortisol",
    "displayName": "Cortisol",
    "aliases": [
      "cortisol",
      "кортизол"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "cortisol"
  },
  {
    "key": "migration_creatinine",
    "analyteKey": "creatinine",
    "displayName": "Creatinine",
    "aliases": [
      "creat",
      "creatinine",
      "креатинин"
    ],
    "specimen": "serum",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 88.4,
      "factorSi": 0.0113,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "creatinine"
  },
  {
    "key": "migration_crp",
    "analyteKey": "crp",
    "displayName": "CRP",
    "aliases": [
      "c_reactive_protein",
      "c_реактивный_белок",
      "crp",
      "срб"
    ],
    "specimen": "unspecified",
    "system": "inflammation",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 10,
      "factorSi": 0.1,
      "siUnit": "mg/L",
      "type": "linear"
    },
    "sourceRecordKey": "crp"
  },
  {
    "key": "migration_d_dimer",
    "analyteKey": "d_dimer",
    "displayName": "D-dimer",
    "aliases": [
      "d_dimer",
      "d_димер",
      "д_димер"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "d_dimer"
  },
  {
    "key": "migration_dhea_s",
    "analyteKey": "dhea_s",
    "displayName": "DHEA-S",
    "aliases": [
      "dhea_s",
      "dhea_sulfate",
      "dheas"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "dhea_s"
  },
  {
    "key": "migration_direct_bilirubin",
    "analyteKey": "direct_bilirubin",
    "displayName": "Direct bilirubin",
    "aliases": [
      "conjugated_bilirubin",
      "direct_bilirubin",
      "билирубин_прямой"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 17.1,
      "factorSi": 0.0585,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "direct_bilirubin"
  },
  {
    "key": "migration_egfr",
    "analyteKey": "egfr",
    "displayName": "eGFR",
    "aliases": [
      "ckd_epi",
      "egfr",
      "egfrcr",
      "estimated_gfr",
      "рскф",
      "скф"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "reason": "eGFR already mL/min/1.73 m²",
      "type": "none"
    },
    "sourceRecordKey": "egfr"
  },
  {
    "key": "migration_eosinophils",
    "analyteKey": "eosinophils",
    "displayName": "Eosinophils (absolute)",
    "aliases": [
      "eosinophils",
      "eosinophils_abs",
      "эозинофилы"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "eosinophils"
  },
  {
    "key": "migration_eosinophils_percent",
    "analyteKey": "eosinophils_percent",
    "displayName": "Eosinophils %",
    "aliases": [
      "eosinophils_percent",
      "эозинофилы_"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "display",
    "conversion": {
      "reason": "Percent",
      "type": "none"
    },
    "sourceRecordKey": "eosinophils_percent"
  },
  {
    "key": "migration_esr",
    "analyteKey": "esr",
    "displayName": "ESR",
    "aliases": [
      "erythrocyte_sedimentation_rate",
      "esr",
      "sedimentation_rate",
      "соэ"
    ],
    "specimen": "unspecified",
    "system": "inflammation",
    "scoreRole": "core",
    "conversion": {
      "reason": "mm/hr",
      "type": "none"
    },
    "sourceRecordKey": "esr"
  },
  {
    "key": "migration_estradiol",
    "analyteKey": "estradiol",
    "displayName": "Estradiol",
    "aliases": [
      "e2",
      "estradiol",
      "эстрадиол"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "estradiol"
  },
  {
    "key": "migration_fasting_glucose",
    "analyteKey": "fasting_glucose",
    "displayName": "Fasting glucose",
    "aliases": [
      "fasting_glucose",
      "fasting_plasma_glucose",
      "fpg",
      "глюкоза_натощак"
    ],
    "specimen": "unspecified",
    "system": "metabolic",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0555,
      "factorSi": 18.02,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "fasting_glucose"
  },
  {
    "key": "migration_ferritin",
    "analyteKey": "ferritin",
    "displayName": "Ferritin",
    "aliases": [
      "ferritin",
      "ферритин"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "ng/mL",
      "siUnit": "µg/L",
      "type": "equal"
    },
    "sourceRecordKey": "ferritin"
  },
  {
    "key": "migration_fibrinogen",
    "analyteKey": "fibrinogen",
    "displayName": "Fibrinogen",
    "aliases": [
      "fibrinogen",
      "фибриноген"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "fibrinogen"
  },
  {
    "key": "migration_folate",
    "analyteKey": "folate",
    "displayName": "Folate",
    "aliases": [
      "folate",
      "folic_acid",
      "vitamin_b9",
      "фолат",
      "фолиевая_кислота"
    ],
    "specimen": "unspecified",
    "system": "nutrients",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "ng/mL",
      "factorCo": 2.265,
      "factorSi": 0.442,
      "siUnit": "nmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "folate"
  },
  {
    "key": "migration_free_t3",
    "analyteKey": "free_t3",
    "displayName": "Free T3",
    "aliases": [
      "free_t3",
      "ft3",
      "св_т3",
      "свободный_т3"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "pg/mL",
      "factorCo": 1.536,
      "factorSi": 0.651,
      "siUnit": "pmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "free_t3"
  },
  {
    "key": "migration_free_t4",
    "analyteKey": "free_t4",
    "displayName": "Free T4",
    "aliases": [
      "free_t4",
      "free_thyroxine",
      "ft4",
      "св_т4",
      "свободный_т4",
      "т4_свободный"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "ng/dL",
      "factorCo": 12.9,
      "factorSi": 0.0775,
      "siUnit": "pmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "free_t4"
  },
  {
    "key": "migration_free_testosterone",
    "analyteKey": "free_testosterone",
    "displayName": "Free testosterone",
    "aliases": [
      "free_testosterone",
      "тестостерон_свободный"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "free_testosterone"
  },
  {
    "key": "migration_fsh",
    "analyteKey": "fsh",
    "displayName": "FSH",
    "aliases": [
      "follicle_stimulating_hormone",
      "fsh"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "fsh"
  },
  {
    "key": "migration_ggt",
    "analyteKey": "ggt",
    "displayName": "GGT",
    "aliases": [
      "gamma_glutamyl_transferase",
      "gamma_gt",
      "ggt",
      "ггт"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "core",
    "conversion": {
      "reason": "Enzyme activity units (U/L); no US/SI mass conversion",
      "type": "none"
    },
    "sourceRecordKey": "ggt"
  },
  {
    "key": "migration_globulin",
    "analyteKey": "globulin",
    "displayName": "Globulin",
    "aliases": [
      "globulin",
      "глобулин"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "g/dL",
      "factorCo": 10,
      "factorSi": 0.1,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "globulin"
  },
  {
    "key": "migration_glucose",
    "analyteKey": "glucose",
    "displayName": "Glucose",
    "aliases": [
      "blood_glucose",
      "blood_sugar",
      "glucose",
      "random_glucose",
      "глюкоза",
      "сахар_крови"
    ],
    "specimen": "unspecified",
    "system": "metabolic",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0555,
      "factorSi": 18.02,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "glucose"
  },
  {
    "key": "migration_hba1c",
    "analyteKey": "hba1c",
    "displayName": "Hemoglobin A1c",
    "aliases": [
      "a1c",
      "glycated_hemoglobin",
      "glycohemoglobin",
      "hb_a1c",
      "hba1c",
      "hemoglobin_a1c",
      "гликированный_гемоглобин",
      "гликогемоглобин"
    ],
    "specimen": "unspecified",
    "system": "metabolic",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "%",
      "formula": "hba1c_ngsp_ifcc",
      "siUnit": "mmol/mol",
      "type": "formula"
    },
    "sourceRecordKey": "hba1c"
  },
  {
    "key": "migration_hdl",
    "analyteKey": "hdl",
    "displayName": "HDL cholesterol",
    "aliases": [
      "hdl",
      "hdl_c",
      "hdl_cholesterol",
      "лпвп",
      "хс_лпвп"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0259,
      "factorSi": 38.61,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "hdl"
  },
  {
    "key": "migration_hematocrit",
    "analyteKey": "hematocrit",
    "displayName": "Hematocrit",
    "aliases": [
      "hct",
      "hematocrit",
      "pcv",
      "гематокрит"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "%",
      "factorCo": 0.01,
      "factorSi": 100,
      "siUnit": "L/L",
      "type": "linear"
    },
    "sourceRecordKey": "hematocrit"
  },
  {
    "key": "migration_hemoglobin",
    "analyteKey": "hemoglobin",
    "displayName": "Hemoglobin",
    "aliases": [
      "hb",
      "hemoglobin",
      "hgb",
      "гемоглобин"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "g/dL",
      "factorCo": 10,
      "factorSi": 0.1,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "hemoglobin"
  },
  {
    "key": "migration_hs_crp",
    "analyteKey": "hs_crp",
    "displayName": "hs-CRP",
    "aliases": [
      "cardiac_crp",
      "high_sensitivity_crp",
      "hs_crp",
      "hscrp",
      "вч_срб"
    ],
    "specimen": "unspecified",
    "system": "inflammation",
    "scoreRole": "core",
    "conversion": {
      "reason": "Usually already mg/L",
      "type": "none"
    },
    "sourceRecordKey": "hs_crp"
  },
  {
    "key": "migration_indirect_bilirubin",
    "analyteKey": "indirect_bilirubin",
    "displayName": "Indirect bilirubin",
    "aliases": [
      "indirect_bilirubin",
      "unconjugated_bilirubin",
      "билирубин_непрямой"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 17.1,
      "factorSi": 0.0585,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "indirect_bilirubin"
  },
  {
    "key": "migration_inr",
    "analyteKey": "inr",
    "displayName": "INR",
    "aliases": [
      "inr",
      "мно"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "inr"
  },
  {
    "key": "migration_insulin",
    "analyteKey": "insulin",
    "displayName": "Insulin",
    "aliases": [
      "insulin",
      "инсулин"
    ],
    "specimen": "unspecified",
    "system": "metabolic",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "µIU/mL",
      "siUnit": "mIU/L",
      "type": "equal"
    },
    "sourceRecordKey": "insulin"
  },
  {
    "key": "migration_iron",
    "analyteKey": "iron",
    "displayName": "Serum iron",
    "aliases": [
      "fe",
      "iron",
      "serum_iron",
      "железо",
      "сывороточное_железо"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "µg/dL",
      "factorCo": 0.179,
      "factorSi": 5.587,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "iron"
  },
  {
    "key": "migration_ldl",
    "analyteKey": "ldl",
    "displayName": "LDL cholesterol",
    "aliases": [
      "ldl",
      "ldl_c",
      "ldl_cholesterol",
      "лпнп",
      "хс_лпнп"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0259,
      "factorSi": 38.61,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "ldl"
  },
  {
    "key": "migration_lh",
    "analyteKey": "lh",
    "displayName": "LH",
    "aliases": [
      "lh",
      "luteinizing_hormone"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "lh"
  },
  {
    "key": "migration_lpa",
    "analyteKey": "lpa",
    "displayName": "Lipoprotein(a)",
    "aliases": [
      "lipoprotein_a",
      "lipoprotein_a_",
      "lp_a",
      "lpa",
      "липопротеин_а",
      "лп_а",
      "лпа"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "extended",
    "conversion": {
      "reason": "Lp(a) mg/dL↔nmol/L not safe with fixed factor",
      "type": "none"
    },
    "sourceRecordKey": "lpa"
  },
  {
    "key": "migration_lymphocytes",
    "analyteKey": "lymphocytes",
    "displayName": "Lymphocytes (absolute)",
    "aliases": [
      "lymphocytes",
      "lymphocytes_abs",
      "лимфоциты"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "lymphocytes"
  },
  {
    "key": "migration_lymphocytes_percent",
    "analyteKey": "lymphocytes_percent",
    "displayName": "Lymphocytes %",
    "aliases": [
      "lymphocytes_percent",
      "лимфоциты_"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "display",
    "conversion": {
      "reason": "Percent",
      "type": "none"
    },
    "sourceRecordKey": "lymphocytes_percent"
  },
  {
    "key": "migration_magnesium",
    "analyteKey": "magnesium",
    "displayName": "Magnesium",
    "aliases": [
      "magnesium",
      "магний"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.4114,
      "factorSi": 2.43,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "magnesium"
  },
  {
    "key": "migration_mch",
    "analyteKey": "mch",
    "displayName": "MCH",
    "aliases": [
      "mch"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "reason": "Already pg",
      "type": "none"
    },
    "sourceRecordKey": "mch"
  },
  {
    "key": "migration_mchc",
    "analyteKey": "mchc",
    "displayName": "MCHC",
    "aliases": [
      "mchc"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "g/dL",
      "factorCo": 10,
      "factorSi": 0.1,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "mchc"
  },
  {
    "key": "migration_mcv",
    "analyteKey": "mcv",
    "displayName": "MCV",
    "aliases": [
      "mcv",
      "mean_corpuscular_volume"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "reason": "Already fL",
      "type": "none"
    },
    "sourceRecordKey": "mcv"
  },
  {
    "key": "migration_monocytes",
    "analyteKey": "monocytes",
    "displayName": "Monocytes (absolute)",
    "aliases": [
      "monocytes",
      "monocytes_abs",
      "моноциты"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "monocytes"
  },
  {
    "key": "migration_monocytes_percent",
    "analyteKey": "monocytes_percent",
    "displayName": "Monocytes %",
    "aliases": [
      "monocytes_percent",
      "моноциты_"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "display",
    "conversion": {
      "reason": "Percent",
      "type": "none"
    },
    "sourceRecordKey": "monocytes_percent"
  },
  {
    "key": "migration_neutrophils",
    "analyteKey": "neutrophils",
    "displayName": "Neutrophils (absolute)",
    "aliases": [
      "absolute_neutrophil_count",
      "anc",
      "neutrophils",
      "neutrophils_abs",
      "нейтрофилы"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "neutrophils"
  },
  {
    "key": "migration_neutrophils_percent",
    "analyteKey": "neutrophils_percent",
    "displayName": "Neutrophils %",
    "aliases": [
      "neutrophils_",
      "neutrophils_percent",
      "нейтрофилы_"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "display",
    "conversion": {
      "reason": "Percent",
      "type": "none"
    },
    "sourceRecordKey": "neutrophils_percent"
  },
  {
    "key": "migration_non_hdl_cholesterol",
    "analyteKey": "non_hdl_cholesterol",
    "displayName": "Non-HDL cholesterol",
    "aliases": [
      "non_hdl",
      "non_hdl_c",
      "non_hdl_cholesterol",
      "не_лпвп",
      "холестерин_не_лпвп"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0259,
      "factorSi": 38.61,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "non_hdl_cholesterol"
  },
  {
    "key": "migration_nt_pro_bnp",
    "analyteKey": "nt_pro_bnp",
    "displayName": "NT-proBNP",
    "aliases": [
      "nt_pro_bnp",
      "ntprobnp"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "nt_pro_bnp"
  },
  {
    "key": "migration_phosphate",
    "analyteKey": "phosphate",
    "displayName": "Phosphate",
    "aliases": [
      "phosphate",
      "phosphorus",
      "po4",
      "фосфат",
      "фосфор"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.323,
      "factorSi": 3.1,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "phosphate"
  },
  {
    "key": "migration_platelets",
    "analyteKey": "platelets",
    "displayName": "Platelets",
    "aliases": [
      "platelets",
      "plt",
      "thrombocytes",
      "тромбоциты"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "platelets"
  },
  {
    "key": "migration_potassium",
    "analyteKey": "potassium",
    "displayName": "Potassium",
    "aliases": [
      "potassium",
      "калий"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mEq/L",
      "siUnit": "mmol/L",
      "type": "equal"
    },
    "sourceRecordKey": "potassium"
  },
  {
    "key": "migration_progesterone",
    "analyteKey": "progesterone",
    "displayName": "Progesterone",
    "aliases": [
      "progesterone",
      "прогестерон"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "progesterone"
  },
  {
    "key": "migration_prolactin",
    "analyteKey": "prolactin",
    "displayName": "Prolactin",
    "aliases": [
      "prolactin",
      "пролактин"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "prolactin"
  },
  {
    "key": "migration_psa",
    "analyteKey": "psa",
    "displayName": "PSA",
    "aliases": [
      "prostate_specific_antigen",
      "psa",
      "пса"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "psa"
  },
  {
    "key": "migration_pt",
    "analyteKey": "pt",
    "displayName": "Prothrombin time",
    "aliases": [
      "prothrombin_time",
      "pt",
      "пв"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "pt"
  },
  {
    "key": "migration_rbc",
    "analyteKey": "rbc",
    "displayName": "RBC",
    "aliases": [
      "erythrocytes",
      "rbc",
      "red_blood_cells",
      "эритроциты"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "rbc"
  },
  {
    "key": "migration_rdw",
    "analyteKey": "rdw",
    "displayName": "RDW",
    "aliases": [
      "rdw",
      "red_cell_distribution_width"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "reason": "Percent / ratio",
      "type": "none"
    },
    "sourceRecordKey": "rdw"
  },
  {
    "key": "migration_remnant_cholesterol",
    "analyteKey": "remnant_cholesterol",
    "displayName": "Remnant cholesterol",
    "aliases": [
      "remnant_c",
      "remnant_cholesterol"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0259,
      "factorSi": 38.61,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "remnant_cholesterol"
  },
  {
    "key": "migration_rf",
    "analyteKey": "rf",
    "displayName": "Rheumatoid factor",
    "aliases": [
      "rf",
      "rheumatoid_factor",
      "ревматоидный_фактор"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "rf"
  },
  {
    "key": "migration_shbg",
    "analyteKey": "shbg",
    "displayName": "SHBG",
    "aliases": [
      "shbg"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "shbg"
  },
  {
    "key": "migration_sodium",
    "analyteKey": "sodium",
    "displayName": "Sodium",
    "aliases": [
      "sodium",
      "натрий"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mEq/L",
      "siUnit": "mmol/L",
      "type": "equal"
    },
    "sourceRecordKey": "sodium"
  },
  {
    "key": "migration_specific_gravity",
    "analyteKey": "specific_gravity",
    "displayName": "Specific gravity",
    "aliases": [
      "sg",
      "specific_gravity",
      "urine_specific_gravity"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "specific_gravity"
  },
  {
    "key": "migration_t3",
    "analyteKey": "t3",
    "displayName": "Total T3",
    "aliases": [
      "t3",
      "total_t3",
      "triiodothyronine",
      "т3",
      "т3_общий"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "ng/dL",
      "factorCo": 0.0154,
      "factorSi": 64.9,
      "siUnit": "nmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "t3"
  },
  {
    "key": "migration_t4",
    "analyteKey": "t4",
    "displayName": "Total T4",
    "aliases": [
      "t4",
      "thyroxine",
      "total_t4",
      "т4",
      "т4_общий"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "µg/dL",
      "factorCo": 12.9,
      "factorSi": 0.0775,
      "siUnit": "nmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "t4"
  },
  {
    "key": "migration_tibc",
    "analyteKey": "tibc",
    "displayName": "TIBC",
    "aliases": [
      "tibc",
      "total_iron_binding_capacity",
      "ожсс"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "µg/dL",
      "factorCo": 0.179,
      "factorSi": 5.587,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "tibc"
  },
  {
    "key": "migration_total_cholesterol",
    "analyteKey": "total_cholesterol",
    "displayName": "Total cholesterol",
    "aliases": [
      "chol",
      "cholesterol_total",
      "tc",
      "total_cholesterol",
      "общий_холестерин",
      "охс",
      "холестерин_общий"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0259,
      "factorSi": 38.61,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "total_cholesterol"
  },
  {
    "key": "migration_total_protein",
    "analyteKey": "total_protein",
    "displayName": "Total protein",
    "aliases": [
      "total_protein",
      "общий_белок"
    ],
    "specimen": "unspecified",
    "system": "liver",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "g/dL",
      "factorCo": 10,
      "factorSi": 0.1,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "total_protein"
  },
  {
    "key": "migration_total_testosterone",
    "analyteKey": "total_testosterone",
    "displayName": "Total testosterone",
    "aliases": [
      "testosterone",
      "total_testosterone",
      "тестостерон",
      "тестостерон_общий"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "total_testosterone"
  },
  {
    "key": "migration_trab",
    "analyteKey": "trab",
    "displayName": "TSH receptor antibodies",
    "aliases": [
      "tbii",
      "trab",
      "tsh_receptor_antibodies",
      "ат_к_рецепторам_ттг"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "extended",
    "conversion": {
      "reason": "Assay-specific antibody units",
      "type": "none"
    },
    "sourceRecordKey": "trab"
  },
  {
    "key": "migration_transferrin",
    "analyteKey": "transferrin",
    "displayName": "Transferrin",
    "aliases": [
      "transferrin",
      "трансферрин"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.01,
      "factorSi": 100,
      "siUnit": "g/L",
      "type": "linear"
    },
    "sourceRecordKey": "transferrin"
  },
  {
    "key": "migration_transferrin_saturation",
    "analyteKey": "transferrin_saturation",
    "displayName": "Transferrin saturation",
    "aliases": [
      "t_sat",
      "transferrin_saturation",
      "tsat",
      "насыщение_трансферрина"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "reason": "Percent",
      "type": "none"
    },
    "sourceRecordKey": "transferrin_saturation"
  },
  {
    "key": "migration_triglycerides",
    "analyteKey": "triglycerides",
    "displayName": "Triglycerides",
    "aliases": [
      "tg",
      "trig",
      "triglycerides",
      "тг",
      "триглицериды"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0113,
      "factorSi": 88.5,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "triglycerides"
  },
  {
    "key": "migration_troponin_i",
    "analyteKey": "troponin_i",
    "displayName": "Troponin I",
    "aliases": [
      "ctni",
      "troponin_i",
      "тропонин_i"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "troponin_i"
  },
  {
    "key": "migration_troponin_t",
    "analyteKey": "troponin_t",
    "displayName": "Troponin T",
    "aliases": [
      "ctnt",
      "troponin_t",
      "тропонин_t"
    ],
    "specimen": "unspecified",
    "system": "general",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "troponin_t"
  },
  {
    "key": "migration_tsh",
    "analyteKey": "tsh",
    "displayName": "TSH",
    "aliases": [
      "thyrotropin",
      "tsh",
      "тиреотропный_гормон",
      "ттг"
    ],
    "specimen": "unspecified",
    "system": "thyroid",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "µIU/mL",
      "siUnit": "mIU/L",
      "type": "equal"
    },
    "sourceRecordKey": "tsh"
  },
  {
    "key": "migration_uacr",
    "analyteKey": "uacr",
    "displayName": "Urine albumin/creatinine ratio",
    "aliases": [
      "acr",
      "albumin_creatinine_ratio",
      "microalbumin_creatinine_ratio",
      "uacr",
      "акр",
      "альбумин_креатинин"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/g",
      "factorCo": 0.113,
      "factorSi": 8.84,
      "siUnit": "mg/mmol",
      "type": "linear"
    },
    "sourceRecordKey": "uacr"
  },
  {
    "key": "migration_uibc",
    "analyteKey": "uibc",
    "displayName": "UIBC",
    "aliases": [
      "uibc",
      "unsaturated_iron_binding_capacity",
      "лжсс",
      "нжсс"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "µg/dL",
      "factorCo": 0.179,
      "factorSi": 5.587,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "uibc"
  },
  {
    "key": "migration_urea",
    "analyteKey": "urea",
    "displayName": "Urea",
    "aliases": [
      "urea",
      "мочевина"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "formula": "bun_urea",
      "siUnit": "mmol/L",
      "type": "formula"
    },
    "sourceRecordKey": "urea"
  },
  {
    "key": "migration_uric_acid",
    "analyteKey": "uric_acid",
    "displayName": "Uric acid",
    "aliases": [
      "urate",
      "uric_acid",
      "мочевая_кислота"
    ],
    "specimen": "unspecified",
    "system": "kidney",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 59,
      "factorSi": 0.0169,
      "siUnit": "µmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "uric_acid"
  },
  {
    "key": "migration_urine_albumin",
    "analyteKey": "urine_albumin",
    "displayName": "Urine albumin",
    "aliases": [
      "microalbumin",
      "urine_albumin",
      "альбумин_в_моче",
      "микроальбумин"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "extended",
    "conversion": null,
    "sourceRecordKey": "urine_albumin"
  },
  {
    "key": "migration_urine_blood_dipstick",
    "analyteKey": "urine_blood_dipstick",
    "displayName": "Urine blood (dipstick)",
    "aliases": [
      "blood_urine",
      "urine_blood",
      "urine_blood_dipstick"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_blood_dipstick"
  },
  {
    "key": "migration_urine_creatinine",
    "analyteKey": "urine_creatinine",
    "displayName": "Urine creatinine",
    "aliases": [
      "urine_creatinine",
      "креатинин_в_моче"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0884,
      "factorSi": 11.31,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "urine_creatinine"
  },
  {
    "key": "migration_urine_glucose_dipstick",
    "analyteKey": "urine_glucose_dipstick",
    "displayName": "Urine glucose (dipstick)",
    "aliases": [
      "glucose_urine",
      "urine_glucose_dipstick"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_glucose_dipstick"
  },
  {
    "key": "migration_urine_ketones",
    "analyteKey": "urine_ketones",
    "displayName": "Urine ketones",
    "aliases": [
      "ketones",
      "urine_ketones",
      "кетоны_мочи"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_ketones"
  },
  {
    "key": "migration_urine_leukocyte_esterase",
    "analyteKey": "urine_leukocyte_esterase",
    "displayName": "Leukocyte esterase",
    "aliases": [
      "leu",
      "leukocyte_esterase",
      "urine_leukocyte_esterase"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_leukocyte_esterase"
  },
  {
    "key": "migration_urine_nitrite",
    "analyteKey": "urine_nitrite",
    "displayName": "Urine nitrite",
    "aliases": [
      "nitrite",
      "urine_nitrite"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_nitrite"
  },
  {
    "key": "migration_urine_ph",
    "analyteKey": "urine_ph",
    "displayName": "Urine pH",
    "aliases": [
      "ph_urine",
      "urine_ph"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_ph"
  },
  {
    "key": "migration_urine_protein",
    "analyteKey": "urine_protein",
    "displayName": "Urine protein",
    "aliases": [
      "urine_protein",
      "белок_в_моче"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "extended",
    "conversion": null,
    "sourceRecordKey": "urine_protein"
  },
  {
    "key": "migration_urine_protein_dipstick",
    "analyteKey": "urine_protein_dipstick",
    "displayName": "Urine protein (dipstick)",
    "aliases": [
      "protein_urine",
      "urine_protein_dipstick",
      "белок_в_моче_кач"
    ],
    "specimen": "urine",
    "system": "kidney",
    "scoreRole": "display",
    "conversion": null,
    "sourceRecordKey": "urine_protein_dipstick"
  },
  {
    "key": "migration_vitamin_d",
    "analyteKey": "vitamin_d",
    "displayName": "Vitamin D (25-OH)",
    "aliases": [
      "25_hydroxyvitamin_d",
      "25_oh_d",
      "25_oh_vitamin_d",
      "25_ohd",
      "25_он_витамин_d",
      "calcidiol",
      "vitamin_d",
      "витамин_d"
    ],
    "specimen": "unspecified",
    "system": "nutrients",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "ng/mL",
      "factorCo": 2.5,
      "factorSi": 0.4,
      "siUnit": "nmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "vitamin_d"
  },
  {
    "key": "migration_vldl",
    "analyteKey": "vldl",
    "displayName": "VLDL cholesterol",
    "aliases": [
      "vldl",
      "vldl_c",
      "vldl_cholesterol"
    ],
    "specimen": "unspecified",
    "system": "cardiovascular",
    "scoreRole": "extended",
    "conversion": {
      "conventionalUnit": "mg/dL",
      "factorCo": 0.0259,
      "factorSi": 38.61,
      "siUnit": "mmol/L",
      "type": "linear"
    },
    "sourceRecordKey": "vldl"
  },
  {
    "key": "migration_wbc",
    "analyteKey": "wbc",
    "displayName": "WBC",
    "aliases": [
      "leukocytes",
      "wbc",
      "white_blood_cells",
      "лейкоциты"
    ],
    "specimen": "unspecified",
    "system": "blood",
    "scoreRole": "core",
    "conversion": {
      "conventionalUnit": "×10³/µL",
      "siUnit": "×10⁹/L",
      "type": "equal"
    },
    "sourceRecordKey": "wbc"
  }
];
