import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const GENERATED_NOTICE = "<!-- This file is generated by scripts/export-biomarker-wiki.ts. Do not edit manually. -->";
const REPOSITORY_URL = "https://github.com/Hazyshades/EasyHealth";

const canonicalSources = [
  ["Biomarker-Architecture.md", "docs/03-modules/biomarkers.md"],
  ["Biomarker-Catalog.md", "docs/05-data/biomarker-catalog.md"],
  ["Biomarker-Aliases.md", "docs/05-data/biomarker-aliases.md"],
  ["Biomarker-Corpus-Evidence.md", "docs/05-data/biomarker-corpus-evidence.md"],
] as const;

export const BIOMARKER_WIKI_PAGES = [
  "Home.md",
  ...canonicalSources.map(([page]) => page),
  "Registry-v1-Legacy.md",
  "_Sidebar.md",
] as const;

function repositoryLink(path: string): string {
  return `${REPOSITORY_URL}/blob/master/${path}`;
}

function transformCanonicalDocument(content: string): string {
  return content
    .replace(/^<!-- This file is generated by scripts\/generate-biomarker-docs\.ts\. Do not edit manually\. -->\n?/, "")
    .replaceAll("(../05-data/biomarker-catalog.md)", "(Biomarker-Catalog)")
    .replaceAll("(../05-data/biomarker-aliases.md)", "(Biomarker-Aliases)")
    .replaceAll("(./biomarker-aliases.md)", "(Biomarker-Aliases)")
    .replaceAll("(../../registry/biomarker-registry/v1.0.0/AUDIT.md)", `(${repositoryLink("registry/biomarker-registry/v1.0.0/AUDIT.md")})`);
}

function legacyFromCatalog(catalog: string): string {
  const start = catalog.indexOf("## Registry v1 legacy boundary");
  if (start === -1) throw new Error("Canonical catalog is missing its Registry v1 legacy boundary");
  return catalog.slice(start).trimEnd();
}

export function renderBiomarkerWiki(root = ROOT): Record<(typeof BIOMARKER_WIKI_PAGES)[number], string> {
  const documents = new Map(
    canonicalSources.map(([page, path]) => [page, transformCanonicalDocument(readFileSync(resolve(root, path), "utf8").trimEnd())]),
  );
  const catalog = documents.get("Biomarker-Catalog.md");
  if (!catalog) throw new Error("Canonical catalog is required for the Wiki legacy page");
  const pageLinks = canonicalSources.map(([page, path]) => `- [${documents.get(page)?.match(/^# (.+)$/m)?.[1] ?? page}](./${page.replace(/\.md$/, "")}) — [canonical source](${repositoryLink(path)})`);
  return {
    "Home.md": [
      GENERATED_NOTICE,
      "# EasyHealth Biomarker Registry 2.0",
      "",
      "This Wiki is a generated, non-authoritative mirror. The canonical documentation lives in the repository links below; regenerate the canonical docs before staging this mirror.",
      "",
      "## Canonical pages",
      "",
      ...pageLinks,
      "- [Registry v1 legacy](./Registry-v1-Legacy) — derived from the canonical Registry 2.0 catalog boundary.",
      "",
    ].join("\n"),
    "Biomarker-Architecture.md": `${GENERATED_NOTICE}\n${documents.get("Biomarker-Architecture.md")}\n`,
    "Biomarker-Catalog.md": `${GENERATED_NOTICE}\n${documents.get("Biomarker-Catalog.md")}\n`,
    "Biomarker-Aliases.md": `${GENERATED_NOTICE}\n${documents.get("Biomarker-Aliases.md")}\n`,
    "Biomarker-Corpus-Evidence.md": `${GENERATED_NOTICE}\n${documents.get("Biomarker-Corpus-Evidence.md")}\n`,
    "Registry-v1-Legacy.md": `${GENERATED_NOTICE}\n${legacyFromCatalog(catalog)}\n`,
    "_Sidebar.md": [
      GENERATED_NOTICE,
      "### Biomarkers",
      "",
      "- [Home](Home)",
      ...canonicalSources.map(([page]) => `- [${page.replace(/\.md$/, "")}](./${page.replace(/\.md$/, "")})`),
      "- [Registry v1 legacy](Registry-v1-Legacy)",
      "",
    ].join("\n"),
  };
}

export function renderBiomarkerWikiJson(root = ROOT): string {
  return `${JSON.stringify(renderBiomarkerWiki(root), null, 2)}\n`;
}

export function writeBiomarkerWiki(output: string, root = ROOT): void {
  const outputDirectory = resolve(root, output);
  if (existsSync(outputDirectory) && readdirSync(outputDirectory).length > 0) {
    throw new Error(`Wiki staging directory must be empty: ${outputDirectory}`);
  }
  mkdirSync(outputDirectory, { recursive: true });
  const pages = renderBiomarkerWiki(root);
  for (const page of BIOMARKER_WIKI_PAGES) writeFileSync(resolve(outputDirectory, page), pages[page], "utf8");
}

function main(): void {
  const args = process.argv.slice(2).filter((argument) => argument !== "--");
  if (args.length === 1 && args[0] === "--render") {
    process.stdout.write(renderBiomarkerWikiJson());
    return;
  }
  const output = args.find((argument) => argument.startsWith("--output="));
  if (args.length === 2 && args.includes("--write") && output) {
    writeBiomarkerWiki(output.slice("--output=".length));
    console.log(`export-biomarker-wiki: wrote ${BIOMARKER_WIKI_PAGES.length} pages to ${resolve(ROOT, output.slice("--output=".length))}`);
    return;
  }
  throw new Error("Usage: tsx scripts/export-biomarker-wiki.ts --render | --write --output=<empty-local-staging-dir>");
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("/scripts/export-biomarker-wiki.ts")) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
