import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type SnapshotDefinition = {
  key: string;
  displayName: string;
  aliases: string[];
  specimen: "serum" | "plasma" | "whole_blood" | "urine" | null;
  system: string;
  scoreRole: string;
  conversion: unknown;
};

type Snapshot = { definitions: SnapshotDefinition[] };

const root = resolve(import.meta.dirname, "..");
const sourcePath = resolve(root, "registry/biomarker-registry/v1.0.0/registry.json");
const outputPath = resolve(root, "src/lib/biomarkers/launch-catalog.generated.ts");
const source = JSON.parse(readFileSync(sourcePath, "utf8")) as Snapshot;

const records = source.definitions
  .slice()
  .sort((left, right) => left.key.localeCompare(right.key))
  .map((definition) => ({
    key: `migration_${definition.key}`,
    analyteKey: definition.key,
    displayName: definition.displayName,
    aliases: [...new Set([definition.key, ...definition.aliases])].sort(),
    specimen: definition.specimen ?? "unspecified",
    system: definition.system,
    scoreRole: definition.scoreRole,
    conversion: definition.conversion,
    sourceRecordKey: definition.key,
  }));

const content = `// Generated by scripts/generate-launch-catalog.ts from the frozen Registry v1 audit fixture.\n// Do not edit by hand; application runtime imports this materialized launch catalog, never Registry v1.\nimport type { LaunchCatalogMigrationRecord } from "./types";\n\nexport const LAUNCH_CATALOG_MIGRATION_RECORDS: readonly LaunchCatalogMigrationRecord[] = ${JSON.stringify(records, null, 2)};\n`;
writeFileSync(outputPath, content, "utf8");
console.log(`Generated ${records.length} launch catalog migration records.`);
