import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  ANALYTES,
  MEASUREMENT_CATALOG_MANIFEST_DIGEST,
  MEASUREMENT_CATALOG_MANIFEST_VERSION,
  MEASUREMENT_DEFINITIONS,
  MEASUREMENT_NORMALIZATION_VERSION,
  MEASUREMENT_RESOLVER_VERSION,
  PANEL_DEFINITIONS,
  PANEL_REGISTRY_VERSION,
  getMeasurementConversionPolicy,
  getMeasurementIdentity,
  getRegistryV2ScoreContributionGroups,
  getRegistryV2ScoreReadinessGroups,
  getRegistryV2ScoreRole,
  getReviewedAssessmentBinding,
  getReviewedScoreContributionGroups,
  getReviewedScoreReadinessGroups,
  validateMeasurementRegistry,
  type AliasDefinition,
  type MeasurementDefinition,
} from "../src/lib/biomarkers";
import { projectHealthProfileLaboratoryInput } from "../src/lib/health-profile-input";
import {
  projectActiveRegistryV2LaboratoryBinding,
  type RegistryV2NormalizationRevisionReadBoundary,
} from "../src/lib/documents/observation-read-boundaries";
import { projectLaboratoryOutcome } from "../src/lib/documents/incomplete-laboratory-outcomes";
import {
  DEFAULT_CANDIDATE_CORPUS_ROOT,
  runRegistryV2CandidateCorpusTechnical,
  type CandidateCorpusReport,
  type CandidateCorpusReportRow,
  type CandidateCorpusTechnicalRun,
} from "./lib/registry-v2-candidate-corpus";

const ROOT = process.cwd();
const LOCALES = ["en", "ru", "es"] as const;
const GENERATED_NOTICE = "<!-- This file is generated by scripts/generate-biomarker-docs.ts. Do not edit manually. -->";
const README_START = "<!-- generated-biomarker-docs:start -->";
const README_END = "<!-- generated-biomarker-docs:end -->";
const BASELINE_PATH = "registry/biomarker-registry/v2.0.0/documentation-baseline.json";

export const BIOMARKER_DOCUMENT_PATHS = {
  module: "docs/03-modules/biomarkers.md",
  catalog: "docs/05-data/biomarker-catalog.md",
  aliases: "docs/05-data/biomarker-aliases.md",
  corpus: "docs/05-data/biomarker-corpus-evidence.md",
} as const;

type DocumentKey = keyof typeof BIOMARKER_DOCUMENT_PATHS;
export type BiomarkerDocumentationOutput = Record<DocumentKey, string>;

export type BiomarkerDocumentationCounts = {
  definitions: number;
  reviewedDefinitions: number;
  provisionalDefinitions: number;
  retiredDefinitions: number;
  analytes: number;
  aliases: number;
  assessmentBoundDefinitions: number;
  aliasesByLocale: Record<string, number>;
};

export type DocumentationBaseline = {
  schemaVersion: "1";
  catalog: {
    manifestVersion: string;
    manifestDigest: string;
    counts: BiomarkerDocumentationCounts;
  };
  technicalCorpus: {
    rows: number;
    rowsByLocale: Record<string, number>;
  };
};

export type BiomarkerDocumentation = {
  files: BiomarkerDocumentationOutput;
  readmeSection: string;
  issueBody: string;
};

function compareStable(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function sortBy<T>(values: readonly T[], key: (value: T) => string): T[] {
  return [...values].sort((left, right) => compareStable(key(left), key(right)));
}

export function escapeMarkdownCell(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, "<br>");
}

function code(value: unknown): string {
  return `\`${escapeMarkdownCell(value)}\``;
}

function list(values: readonly unknown[], empty = "—"): string {
  return values.length > 0 ? values.map(escapeMarkdownCell).join(", ") : empty;
}

function contributionGroups(values: readonly { id: string; keys: readonly string[] }[]): string {
  return values.length > 0
    ? values.map((group) => `${code(group.id)}: ${list(group.keys.map(code))}`).join("; ")
    : "—";
}

function readBaseline(root = ROOT): DocumentationBaseline {
  const baseline = JSON.parse(readFileSync(resolve(root, BASELINE_PATH), "utf8")) as DocumentationBaseline;
  if (baseline.schemaVersion !== "1") throw new Error("Documentation baseline has an unsupported schema version");
  return baseline;
}

export function getBiomarkerDocumentationCounts(
  definitions: readonly MeasurementDefinition[] = MEASUREMENT_DEFINITIONS,
  analyteCount = ANALYTES.length,
): BiomarkerDocumentationCounts {
  const aliases = definitions.flatMap((definition) => definition.aliases);
  const aliasesByLocale: Record<string, number> = {};
  for (const alias of aliases) {
    const locale = alias.locale ?? "unknown";
    aliasesByLocale[locale] = (aliasesByLocale[locale] ?? 0) + 1;
  }
  return {
    definitions: definitions.length,
    reviewedDefinitions: definitions.filter((definition) => definition.maturity === "reviewed").length,
    provisionalDefinitions: definitions.filter((definition) => definition.maturity === "provisional").length,
    retiredDefinitions: definitions.filter((definition) => definition.maturity === "retired").length,
    analytes: analyteCount,
    aliases: aliases.length,
    assessmentBoundDefinitions: definitions.filter((definition) => definition.assessmentBindings.length > 0).length,
    aliasesByLocale,
  };
}

function sameCounts(actual: BiomarkerDocumentationCounts, expected: BiomarkerDocumentationCounts): string[] {
  const failures: string[] = [];
  for (const key of ["definitions", "reviewedDefinitions", "provisionalDefinitions", "retiredDefinitions", "analytes", "aliases", "assessmentBoundDefinitions"] as const) {
    if (actual[key] !== expected[key]) failures.push(`${key}=${actual[key]} (baseline ${expected[key]})`);
  }
  for (const locale of LOCALES) {
    if ((actual.aliasesByLocale[locale] ?? 0) !== (expected.aliasesByLocale[locale] ?? 0)) {
      failures.push(`aliases.${locale}=${actual.aliasesByLocale[locale] ?? 0} (baseline ${expected.aliasesByLocale[locale] ?? 0})`);
    }
  }
  return failures;
}

export function validateBiomarkerDocumentationDefinitions(definitions: readonly MeasurementDefinition[]): string[] {
  const errors = [...validateMeasurementRegistry(definitions).errors];
  const definitionKeys = new Set<string>();
  const aliasKeys = new Set<string>();
  for (const definition of definitions) {
    if (definitionKeys.has(definition.key)) errors.push(`Duplicate measurement definition key: ${definition.key}`);
    definitionKeys.add(definition.key);
    for (const alias of definition.aliases) {
      if (aliasKeys.has(alias.key)) errors.push(`Duplicate alias key: ${alias.key}`);
      aliasKeys.add(alias.key);
      if (alias.measurementDefinitionKey !== definition.key) {
        errors.push(`Alias ${alias.key} has mismatched owner ${alias.measurementDefinitionKey}`);
      }
      if (!alias.locale || !LOCALES.includes(alias.locale as (typeof LOCALES)[number])) {
        errors.push(`Alias ${alias.key} has an unsupported locale`);
      }
      if (!alias.provenance?.kind || !alias.provenance.sourceRecordKey || !alias.matchAuthority || !alias.approvalStatus || !alias.lifecycle) {
        errors.push(`Alias ${alias.key} is missing governance metadata`);
      }
    }
    for (const binding of definition.assessmentBindings) {
      if (binding.status === "reviewed" && binding.compatibility === "compatible" && (
        !binding.assessmentInputKey || !binding.system || !binding.scoreRole || binding.coversConfidence === undefined
      )) {
        errors.push(`Reviewed compatible assessment binding is missing runtime metadata: ${definition.key}`);
      }
    }
  }
  return [...new Set(errors)].sort(compareStable);
}

export function validateBiomarkerDocumentationInputs(
  definitions: readonly MeasurementDefinition[],
  counts: BiomarkerDocumentationCounts,
  baseline: DocumentationBaseline,
  technical: CandidateCorpusTechnicalRun,
): void {
  const errors = validateBiomarkerDocumentationDefinitions(definitions);
  if (baseline.catalog.manifestVersion !== MEASUREMENT_CATALOG_MANIFEST_VERSION) {
    errors.push(`Baseline manifest version ${baseline.catalog.manifestVersion} does not match runtime ${MEASUREMENT_CATALOG_MANIFEST_VERSION}`);
  }
  if (baseline.catalog.manifestDigest !== MEASUREMENT_CATALOG_MANIFEST_DIGEST) {
    errors.push(`Baseline manifest digest ${baseline.catalog.manifestDigest} does not match runtime ${MEASUREMENT_CATALOG_MANIFEST_DIGEST}`);
  }
  errors.push(...sameCounts(counts, baseline.catalog.counts));
  if (technical.report.rows.length !== baseline.technicalCorpus.rows) {
    errors.push(`technical corpus rows=${technical.report.rows.length} (baseline ${baseline.technicalCorpus.rows})`);
  }
  for (const locale of LOCALES) {
    const actual = technical.report.segments.language[locale]?.total ?? 0;
    const expected = baseline.technicalCorpus.rowsByLocale[locale] ?? 0;
    if (actual !== expected) errors.push(`technical corpus ${locale}=${actual} (baseline ${expected})`);
  }
  if (technical.manifest.fixtureErrors.length > 0) errors.push(...technical.manifest.fixtureErrors);
  for (const check of technical.manifest.thresholdChecks) if (!check.passed) errors.push(`technical corpus threshold failed: ${check.metric}`);
  if (errors.length > 0) throw new Error(`Cannot generate biomarker documentation:\n${errors.map((error) => `- ${error}`).join("\n")}`);
}

function aliasGroups(definition: MeasurementDefinition): Map<string, AliasDefinition[]> {
  const groups = new Map<string, AliasDefinition[]>();
  for (const locale of LOCALES) groups.set(locale, []);
  for (const alias of definition.aliases) groups.get(alias.locale ?? "unknown")?.push(alias);
  for (const aliases of groups.values()) aliases.sort((left, right) => compareStable(left.key, right.key));
  return groups;
}

function formatConversion(definition: MeasurementDefinition): string {
  const conversion = getMeasurementConversionPolicy(definition.key);
  if (!conversion) return "none (no reviewed conversion rule)";
  if (conversion.type === "linear") return `linear: ${conversion.conventionalUnit} → ${conversion.siUnit} × ${conversion.factorCo}; ${conversion.siUnit} → ${conversion.conventionalUnit} × ${conversion.factorSi}`;
  if (conversion.type === "equal") return `equal: ${conversion.conventionalUnit} = ${conversion.siUnit}`;
  if (conversion.type === "formula") return `formula ${code(conversion.formula)}: ${conversion.conventionalUnit} ↔ ${conversion.siUnit}`;
  return `none: ${conversion.reason}`;
}

function projectEligibility(definition: MeasurementDefinition) {
  const relation: RegistryV2NormalizationRevisionReadBoundary = {
    resolver_result: "resolved",
    verification_status: "user_verified",
    measurement_definition_key: definition.key,
    is_active: true,
    resolver_evidence: { version: 2, selectedCandidateKey: definition.key, outcome: "resolved" },
  };
  const observation = {
    observation_kind: "lab" as const,
    measurement_definition_key: definition.key,
    resolution_status: "resolved",
    name: definition.displayName,
    value: 1,
    unit: definition.unitPolicy.canonicalUnit ?? "",
    ref_low: 0,
    ref_high: 2,
    raw_reference_text: "0–2",
    observed_at: "2000-01-01",
    document_id: "documentation-fixture",
    value_kind: "numeric",
    value_text: "1",
    ordinal: null,
    specimen: definition.specimen,
    modifier: definition.timing,
  };
  const binding = projectActiveRegistryV2LaboratoryBinding(observation, relation);
  const outcome = projectLaboratoryOutcome({ observation, relation });
  const input = projectHealthProfileLaboratoryInput({ observation, relation, labUnitSystem: "si" });
  const reviewedBinding = getReviewedAssessmentBinding(definition.key);
  const system = reviewedBinding?.binding.system ?? "general";
  return {
    eligible: input !== null,
    binding,
    outcome,
    reviewedBinding,
    scoreRole: getRegistryV2ScoreRole(definition.key),
    readinessGroups: getRegistryV2ScoreReadinessGroups(system),
    contributionGroups: getRegistryV2ScoreContributionGroups(system),
    reviewedReadinessGroups: getReviewedScoreReadinessGroups(system),
    reviewedContributionGroups: getReviewedScoreContributionGroups(system),
  };
}

function renderAliasesByLocale(definition: MeasurementDefinition): string {
  const groups = aliasGroups(definition);
  return LOCALES.map((locale) => {
    const aliases = groups.get(locale) ?? [];
    const rendered = aliases.length === 0 ? "—" : aliases.map((alias) => `${escapeMarkdownCell(alias.value)} [${code(alias.key)}${alias.laboratory ? `; laboratory=${code(alias.laboratory)}` : ""}]`).join(" · ");
    return `- **${locale}** (${aliases.length}): ${rendered}`;
  }).join("\n");
}

function renderDefinition(definition: MeasurementDefinition): string {
  const [analyteKey, specimen, property, scale, timing, method, valueKind] = getMeasurementIdentity(definition);
  const projection = projectEligibility(definition);
  const definitionBinding = projection.reviewedBinding?.binding;
  return [
    `### ${code(definition.key)} — ${escapeMarkdownCell(definition.displayName)}`,
    "",
    `- **analyte:** ${code(analyteKey)}`,
    `- **specimen / property / scale:** ${code(specimen)} / ${code(property)} / ${code(scale)}`,
    `- **timing / method / value kind:** ${code(timing)} / ${code(method)} / ${code(valueKind)}`,
    `- **maturity:** ${code(definition.maturity)}; **definition provenance:** ${code(definition.sourceProvenance.kind)} / ${code(definition.sourceProvenance.sourceRecordKey)}`,
    `- **concrete-resolution eligibility:** ${definition.maturity === "reviewed" ? "reviewed identity may resolve only after authorized label and clinical-axis compatibility" : "recognition-only; cannot select a concrete identity"}`,
    `- **unit dimensions:** ${list(definition.unitPolicy.dimensions.map(code))}; **accepted units:** ${list(definition.unitPolicy.acceptedUnits.map(code))}; **canonical unit:** ${code(definition.unitPolicy.canonicalUnit)}`,
    `- **conversion policy:** ${code(definition.unitPolicy.conversionPolicyRef)}; **missing-unit behavior:** ${code(definition.unitPolicy.missingUnitPolicy)}; **conversion:** ${formatConversion(definition)}`,
    `- **required modifiers / methods:** ${list((definition.requiredModifiers ?? []).map(code))} / ${list((definition.requiredMethods ?? []).map(code))}`,
    `- **Health Profile consumer eligibility:** ${projection.eligible ? "yes" : "no"}. It requires a lab observation, active \`resolved\` revision/trace, matching selected candidate and definition key, reviewed Registry v2 provenance, and a reviewed compatible assessment binding.`,
    `- **reviewed binding:** ${definitionBinding ? `${code(definitionBinding.assessmentInputKey)}; system=${code(definitionBinding.system)}; compatibility=${code(definitionBinding.compatibility)}; status=${code(definitionBinding.status)}` : "—"}`,
    `- **score role / readiness / contribution groups:** ${code(projection.scoreRole)} / ${list(projection.readinessGroups.map(code))} / ${contributionGroups(projection.contributionGroups)}`,
    `- **reviewed groups:** readiness ${list(projection.reviewedReadinessGroups.map(code))}; contribution ${contributionGroups(projection.reviewedContributionGroups)}`,
    "",
    "**Compact aliases by locale**",
    renderAliasesByLocale(definition),
    "",
  ].join("\n");
}

function renderPanels(): string[] {
  const rows = sortBy(PANEL_DEFINITIONS, (panel) => panel.key).map((panel) => [
    code(panel.key),
    escapeMarkdownCell(panel.displayName),
    list(panel.alternateNames),
    panel.members
      .slice()
      .sort((left, right) => left.displayOrder - right.displayOrder)
      .map((member) => `${member.displayOrder}. ${code(member.measurementDefinitionKey)} (${member.role})`)
      .join("<br>"),
  ].join(" | "));
  return [
    "## Static panel registry",
    "",
    `Panel registry version ${code(PANEL_REGISTRY_VERSION)}. Membership is static catalog metadata; it does not resolve measurements, supply specimen, change assessment bindings, or alter scoring.`,
    "",
    "| panel key | canonical name | alternate names | ordered members |",
    "| --- | --- | --- | --- |",
    ...rows.map((row) => `| ${row} |`),
    "",
  ];
}

function renderCatalog(definitions: readonly MeasurementDefinition[], counts: BiomarkerDocumentationCounts): string {
  const reviewed = sortBy(definitions.filter((definition) => definition.maturity === "reviewed"), (definition) => definition.key);
  const provisional = sortBy(definitions.filter((definition) => definition.maturity === "provisional"), (definition) => definition.key);
  return [
    GENERATED_NOTICE,
    "# Registry 2.0 Biomarker Catalog",
    "",
    "Canonical reference generated from the typed runtime Registry 2.0 catalog. A measurement definition is not merely an analyte: its identity includes analyte, specimen, property, scale, timing, method, and value kind.",
    "",
    `- **Definitions:** ${counts.definitions} (${counts.reviewedDefinitions} reviewed; ${counts.provisionalDefinitions} provisional). **Analytes:** ${counts.analytes}.`,
    `- **Aliases:** ${counts.aliases} (${LOCALES.map((locale) => `${locale} ${counts.aliasesByLocale[locale] ?? 0}`).join("; ")}). **Assessment-bound definitions:** ${counts.assessmentBoundDefinitions}.`,
    `- **Manifest:** ${code(MEASUREMENT_CATALOG_MANIFEST_VERSION)} / ${code(MEASUREMENT_CATALOG_MANIFEST_DIGEST)}; resolver ${code(MEASUREMENT_RESOLVER_VERSION)}; normalization ${code(MEASUREMENT_NORMALIZATION_VERSION)}.`,
    "",
    "The [complete alias-governance reference](./biomarker-aliases.md) is authoritative for alias authority, approval, lifecycle, fixture, provenance, and review metadata.",
    "",
    `## Reviewed definitions (${reviewed.length})`,
    "",
    ...reviewed.map(renderDefinition),
    `## Provisional definitions (${provisional.length})`,
    "",
    "Provisional definitions preserve recognition evidence only. Even a synthetic resolved trace is rejected by the real consumer projection because maturity/provenance is not reviewed; they never enter Health Profile or scoring.",
    "",
    ...provisional.map(renderDefinition),
    ...renderPanels(),
    "## Registry v1 legacy boundary",
    "",
    "Registry v1 is a frozen compatibility baseline, not a Registry 2.0 runtime source. Its authoritative [v1.0.0 audit](../../registry/biomarker-registry/v1.0.0/AUDIT.md) retains the 113-concept inventory. No v1 concept or alias is automatically promoted or used as a runtime fallback.",
    "",
  ].join("\n");
}

function renderAliases(definitions: readonly MeasurementDefinition[], counts: BiomarkerDocumentationCounts): string {
  const aliases = sortBy(definitions.flatMap((definition) => definition.aliases), (alias) => `${alias.locale}|${alias.measurementDefinitionKey}|${alias.key}`);
  const rows = aliases.map((alias) => [
    alias.locale,
    code(alias.measurementDefinitionKey),
    code(alias.key),
    escapeMarkdownCell(alias.value),
    code(alias.normalizedValue),
    code(alias.source),
    code(alias.matchType),
    code(alias.matchAuthority),
    code(alias.approvalStatus),
    code(alias.lifecycle),
    escapeMarkdownCell(alias.laboratory),
    `${code(alias.provenance.kind)} / ${code(alias.provenance.sourceRecordKey)}`,
    code(alias.reviewReference),
    list((alias.fixtureRefs ?? []).map(code)),
  ].join(" | "));
  return [
    GENERATED_NOTICE,
    "# Registry 2.0 Biomarker Alias Governance",
    "",
    `One generated governance row for every runtime alias: ${counts.aliases} total (${LOCALES.map((locale) => `${locale} ${counts.aliasesByLocale[locale] ?? 0}`).join("; ")}). Verbatim values are not translated; normalized values are the resolver admission form.`,
    "",
    "| locale | definition | alias key | verbatim value | normalized value | source | match type | authority | approval | lifecycle | laboratory restriction | provenance | review reference | fixture references |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows.map((row) => `| ${row} |`),
    "",
  ].join("\n");
}

function corpusSafety(row: CandidateCorpusReportRow): string {
  if (row.actualClassification === "resolved") return row.classificationMatches ? "Safe concrete resolution: reviewed expected definition selected." : "Unsafe classification mismatch.";
  if (row.actualClassification === "partial") return row.classificationMatches ? "Safe incomplete outcome: an identity axis remains insufficient." : "Incomplete outcome differs from expectation.";
  if (row.actualClassification === "ambiguous") return row.classificationMatches ? "Safe non-concrete outcome: candidates remain unresolved." : "Ambiguity differs from expectation.";
  if (row.actualClassification === "unmapped") return row.classificationMatches ? "Safe unmapped outcome: raw evidence remains and catalog does not grow." : "Unmapped outcome differs from expectation.";
  return "Processing error requires investigation.";
}

function renderCorpus(report: CandidateCorpusReport): string {
  const segments = sortBy(Object.entries(report.segments.language), ([locale]) => locale)
    .map(([locale, segment]) => `| ${locale} | ${segment.total} | ${segment.resolved} | ${segment.partial} | ${segment.ambiguous} | ${segment.unmapped} | ${segment.expectedClassificationFailures} | ${segment.falseConcreteResolutions} | ${segment.processingErrors} |`);
  const rows = sortBy(report.rows, (row) => row.id).map((row) => {
    const expected = `${row.expectedClassification}${row.expectedMeasurementDefinitionKey ? ` / ${row.expectedMeasurementDefinitionKey}` : ""}`;
    const actual = `${row.actualClassification ?? "error"}${row.actualMeasurementDefinitionKey ? ` / ${row.actualMeasurementDefinitionKey}` : ""}`;
    const aliasEvidence = row.aliasMatchTypes.length === 0 ? "—" : row.aliasMatchTypes.join(", ");
    return `| ${escapeMarkdownCell(row.id)} | ${escapeMarkdownCell(row.language)} | ${escapeMarkdownCell(row.rawEvidence.label)} | ${escapeMarkdownCell(`${row.rawEvidence.unit ?? "no unit"} / ${row.rawEvidence.valueText}`)} | ${escapeMarkdownCell(expected)} | ${escapeMarkdownCell(actual)} | ${row.falseConcreteResolution ? "yes" : "no"} | ${escapeMarkdownCell(aliasEvidence)} | ${escapeMarkdownCell(corpusSafety(row))} |`;
  });
  return [
    GENERATED_NOTICE,
    "# Registry 2.0 Biomarker Corpus Evidence",
    "",
    "Technical resolver evidence only. This document is independent from the release-governance record.",
    "",
    `- **Rows:** ${report.rows.length}; **expected classification rate:** ${report.metrics.expectedClassificationRate}; **false concrete resolutions:** ${report.metrics.falseConcreteResolutions}; **processing errors:** ${report.metrics.processingErrors}.`,
    "",
    "## Language segments",
    "",
    "| language | total | resolved | partial | ambiguous | unmapped | expected failures | false-concrete | processing errors |",
    "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ...segments,
    "",
    "## Row evidence",
    "",
    "Unknown-marker rows remain `unmapped`; uploads never silently create definitions or aliases.",
    "",
    "| row | language | raw label | unit / value | expected | actual | false-concrete | alias evidence | safety rationale |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

function renderModule(counts: BiomarkerDocumentationCounts): string {
  return [
    GENERATED_NOTICE,
    "# Biomarkers and Registry 2.0",
    "",
    `Registry 2.0 has ${counts.definitions} typed measurement definitions across ${counts.analytes} analytes and ${counts.aliases} EN/RU/ES aliases. Definition identity is analyte plus specimen, property, scale, timing, method, and value kind.`,
    "",
    "## Actual lifecycle",
    "",
    "`worker/src/pipeline.ts` extracts laboratory rows with `extractPipelineBiomarkersFromText` or `extractPipelineBiomarkersFromImage` and first inserts raw evidence into `document_extracted_biomarkers` with `status='needs_review'`: raw label, numeric/text value, unit/raw unit, `document_id`, `profile_id`, and source page/text. A clinical axis such as specimen can be preserved only when its lexical form is captured with that row's source text or section context; an omitted structured field may be recovered from that captured row evidence, but the system never fabricates an unstated axis. Initial extraction does not call `resolveMeasurementDefinition` and does not persist a resolver outcome. `document_type` remains on `documents.document_type`, not on an extracted or observation row.",
    "",
    "`GET /api/documents/[id]/biomarkers` returns the raw extracted row and computes a `buildNormalizationReview` preview. Preview is not persistence. Explicit acceptance (`POST .../biomarkers/accept`), correction or confirmation (`PATCH .../biomarkers`), and operator Registry batch reprocessing use `writeExtractedBiomarkerNormalization`, which calls `write_observation_normalization_revision_v2`. Each persists one source-linked observation and an active normalization revision for `resolved`, `partial`, `ambiguous`, or `unmapped`: raw evidence and document linkage remain on the observation; result/trace remain on the revision and project back to the extracted row.",
    "The review UI draws a source-region overlay only for persisted, page-coherent exact positional provenance on the displayed page. Fuzzy, ambiguous, model-origin, cross-page, legacy, missing-layer, and invalid regions remain page-only so the UI never presents an unverified rectangle as fact; pointer hover and keyboard focus do not navigate or scroll, while explicit selection retains the page affordance.",
    "",
    "## Resolver outcomes and consumers",
    "",
    "| outcome | concrete definition | verification | default record lifecycle | Health Profile |",
    "| --- | --- | --- | --- | --- |",
    "| `resolved` | concrete reviewed definition | `user_verified` on acceptance; `auto_verified` only from the approved service quality gate | `active` | eligible only when verified, numeric, source-range-backed, and covered by a reviewed compatible binding |",
    "| `partial` | none; analyte tier only if supplied by resolver | `pending` | `active` until an explicit lifecycle transition | not eligible |",
    "| `ambiguous` | none; analyte tier only if supplied by resolver | `pending` | `active` until an explicit lifecycle transition | not eligible |",
    "| `unmapped` | none | `pending` | `active` until an explicit lifecycle transition | not eligible |",
    "",
    "## Document review and lifecycle",
    "",
    "`GET /api/documents/[id]/biomarkers` and document bootstrap responses expose `recordStatus`, `sourceIsCurrent`, persisted or preview `traceState`, and `actionAvailability`. The review UI renders resolver outcome, verification status, and record lifecycle as independent labels. Raw acceptance keeps incomplete evidence without verification; rejection requires an owner-scoped reason and current source/revision confirmation; automatic verification is service-only. Once every current published extracted row leaves `needs_review` or `pending_review`, the acceptance endpoint transitions the document from `needs_review` to `ready` / `completed`; a partial acceptance leaves the document reviewable and the action available.",
    "",
    "`rejected` and `superseded` are record-lifecycle states, not verification statuses. Their source rows remain available as historical/raw evidence with stable non-PII reason codes, but are read-only and excluded from current observation, batch-verification, correction, reversal, and Health Profile projections. Reprocessing supersedes laboratory sources through the lifecycle seam instead of deleting raw evidence or normalization history.",
    "",
    "## Health Profile projection",
    "",
    "`GET /api/health-profile` admits laboratory input only through `projectHealthProfileLaboratoryInput`. The source must be current and active, have an active `resolved` trace whose selected candidate matches the measurement definition, use reviewed Registry v2 provenance, have a reviewed compatible assessment binding, and be `auto_verified`, `user_verified`, or `manually_corrected`. Its value must be finite and numeric, and its source document must retain a non-blank printed reference range with at least one finite non-inverted boundary. `GET /api/biomarkers` returns a stable assessment exclusion reason and safe non-inclusion guidance when any gate fails; it does not call the source laboratory result invalid. Registry, population, and generic ranges are never substituted. Once admitted, score role, specimen, readiness group, and contribution group policies still govern scoring. A named system receives a numeric current-state score only when every approved readiness group has one usable `core` alternative; a missing group returns an ordered `missing` reason, and a present but unusable group returns `invalid`. Neither case produces a partial score or `0`. Incomplete, rejected, superseded, provisional, unverified, qualitative, range-ineligible, or non-laboratory observations remain readable evidence but do not enter the scored profile.",
    "",
    "Chart-facing `GET /api/biomarkers` and `GET /api/health-profile` responses emit `Cache-Control: no-store`, so corrections are not served from an HTTP cache. Health Profile reads the latest assessment, job, and synthesis state without generating synthesis during `GET`. When a persisted assessment has a non-succeeded recalculation job, the response reports `assessment_freshness: \"outdated\"`, returns `null` named-system and overall scores, and adds an `outdated` readiness reason to every named system while retaining factual source evidence.",
    "",
    "## Unknown labels and controlled reprocessing",
    "",
    "An unknown label remains raw extracted evidence and becomes persisted `unmapped` only after acceptance or explicit Registry batch reprocessing. `scripts/reprocess-batch.ts` invokes the operator-controlled batch path. There is no HTTP Registry-batch endpoint, automatic catalog-change reprocessing, automatic catalog growth from patient or LLM input, admin queue promoting unknown labels, or source-document-to-catalog provenance promotion.",
    "",
    "## Locales, units, and legacy",
    "",
    "Aliases carry explicit EN/RU/ES locale metadata. Russian uses Unicode-aware label normalization; Spanish accent-fold fallback is collision-gated. Laboratory restrictions never replace locale metadata. Missing units follow each definition policy; conversions are reviewed presentation rules and do not erase raw evidence.",
    "",
    "Registry v1 is frozen compatibility history. The authoritative [v1.0.0 audit](../../registry/biomarker-registry/v1.0.0/AUDIT.md) holds its 113 concepts; this guide does not duplicate them. A v1 item is never automatically promoted, admitted as an alias, or used as a runtime fallback.",
    "",
    "## Source and verification",
    "",
    "- Runtime catalog: `src/lib/biomarkers`.",
    "- Regenerate: `pnpm generate:biomarker-docs`.",
    "- Drift check: `pnpm check:biomarker-docs`.",
    "- Contract test: `pnpm test:biomarker-docs`.",
    "",
  ].join("\n");
}

function renderReadmeSection(counts: BiomarkerDocumentationCounts): string {
  return [
    "## Generated biomarker reference data",
    "",
    `Registry 2.0 biomarker references are generated from the typed catalog and approval-independent technical corpus (${counts.definitions} definitions; ${counts.aliases} EN/RU/ES aliases). Do not edit generated files manually.`,
    "",
    "```text",
    "pnpm generate:biomarker-docs",
    "pnpm check:biomarker-docs",
    "pnpm test:biomarker-docs",
    "```",
  ].join("\n");
}

function renderIssueBody(counts: BiomarkerDocumentationCounts, report: CandidateCorpusReport): string {
  return [
    "# Registry 2.0 biomarker documentation",
    "",
    "`docs/` is canonical; this is an index and tracking body, not a catalog.",
    "",
    `- ${counts.definitions} definitions (${counts.reviewedDefinitions} reviewed; ${counts.provisionalDefinitions} provisional), ${counts.analytes} analytes, and ${counts.aliases} EN/RU/ES aliases.`,
    `- ${report.rows.length} technical corpus rows; expected classification ${report.metrics.expectedClassificationRate * 100}%, false-concrete ${report.metrics.falseConcreteResolutions}, processing errors ${report.metrics.processingErrors}.`,
    "- [Module lifecycle](../blob/master/docs/03-modules/biomarkers.md)",
    "- [Definition catalog](../blob/master/docs/05-data/biomarker-catalog.md)",
    "- [Alias governance](../blob/master/docs/05-data/biomarker-aliases.md)",
    "- [Technical corpus evidence](../blob/master/docs/05-data/biomarker-corpus-evidence.md)",
    "",
    "```text",
    "pnpm generate:biomarker-docs",
    "pnpm check:biomarker-docs",
    "pnpm test:biomarker-docs",
    "```",
    "",
    "Remaining gaps: no automatic catalog promotion from uploads, no admin review/promotion queue, no automatic historical reprocessing, and no HTTP Registry batch administration.",
    "",
  ].join("\n");
}

export function buildBiomarkerDocumentation(root = ROOT): BiomarkerDocumentation {
  const definitions = sortBy(MEASUREMENT_DEFINITIONS, (definition) => definition.key);
  const counts = getBiomarkerDocumentationCounts(definitions);
  const baseline = readBaseline(root);
  const technical = runRegistryV2CandidateCorpusTechnical({ root: resolve(root, DEFAULT_CANDIDATE_CORPUS_ROOT) });
  validateBiomarkerDocumentationInputs(definitions, counts, baseline, technical);
  const files: BiomarkerDocumentationOutput = {
    module: renderModule(counts),
    catalog: renderCatalog(definitions, counts),
    aliases: renderAliases(definitions, counts),
    corpus: renderCorpus(technical.report),
  };
  return { files, readmeSection: renderReadmeSection(counts), issueBody: renderIssueBody(counts, technical.report) };
}

export function replaceReadmeSection(content: string, section: string): string {
  const starts = [...content.matchAll(/<!-- generated-biomarker-docs:start -->/g)];
  const ends = [...content.matchAll(/<!-- generated-biomarker-docs:end -->/g)];
  if (starts.length !== 1 || ends.length !== 1 || starts[0]!.index! >= ends[0]!.index!) {
    throw new Error("docs/README.md must contain exactly one correctly ordered generated biomarker marker pair");
  }
  const before = content.slice(0, starts[0]!.index! + README_START.length);
  const after = content.slice(ends[0]!.index!);
  return `${before}\n${section}\n${after}`;
}

export function staleBiomarkerDocumentationFiles(root = ROOT, documentation = buildBiomarkerDocumentation(root)): string[] {
  const stale = (Object.entries(BIOMARKER_DOCUMENT_PATHS) as Array<[DocumentKey, string]>)
    .filter(([key, path]) => {
      try {
        return readFileSync(resolve(root, path), "utf8") !== documentation.files[key];
      } catch {
        return true;
      }
    })
    .map(([, path]) => path);
  try {
    const readme = readFileSync(resolve(root, "docs/README.md"), "utf8");
    if (replaceReadmeSection(readme, documentation.readmeSection) !== readme) stale.push("docs/README.md (managed biomarker section)");
  } catch {
    stale.push("docs/README.md (managed biomarker section)");
  }
  return stale;
}

export function writeBiomarkerDocumentation(root = ROOT, documentation = buildBiomarkerDocumentation(root)): void {
  const readmePath = resolve(root, "docs/README.md");
  const nextReadme = replaceReadmeSection(readFileSync(readmePath, "utf8"), documentation.readmeSection);
  for (const [key, relativePath] of Object.entries(BIOMARKER_DOCUMENT_PATHS) as Array<[DocumentKey, string]>) {
    const path = resolve(root, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, documentation.files[key], "utf8");
  }
  writeFileSync(readmePath, nextReadme, "utf8");
}

function main(): void {
  const [mode] = process.argv.slice(2);
  if (!mode || !["--write", "--check", "--issue-body"].includes(mode) || process.argv.length > 3) {
    throw new Error("Usage: tsx scripts/generate-biomarker-docs.ts --write|--check|--issue-body");
  }
  const documentation = buildBiomarkerDocumentation();
  if (mode === "--issue-body") {
    process.stdout.write(documentation.issueBody);
    return;
  }
  if (mode === "--check") {
    const stale = staleBiomarkerDocumentationFiles(ROOT, documentation);
    if (stale.length > 0) throw new Error(`Biomarker documentation is stale:\n${stale.map((path) => `- ${path}`).join("\n")}`);
    console.log("check:biomarker-docs: generated files are current");
    return;
  }
  writeBiomarkerDocumentation(ROOT, documentation);
  console.log(`generate:biomarker-docs: wrote ${Object.keys(BIOMARKER_DOCUMENT_PATHS).length} files and the README managed section`);
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("/scripts/generate-biomarker-docs.ts")) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
