import assert from "node:assert/strict";
import { measurementMappingGuidance, measurementMappingLabel, resolveBiomarkerPanelMode, resolveBiomarkerReviewAction, reviewDataErrorMessage, validateObservationFallbackConfirmation } from "../src/lib/documents/biomarker-review-state";
assert.equal(measurementMappingLabel("partial", "medium"), "More details needed");
assert.equal(measurementMappingLabel("unmapped", "low"), "Measurement not recognized");
assert.equal(measurementMappingLabel("resolved", "high"), "Matched measurement");
assert.match(measurementMappingGuidance("partial"), /required context is missing/);
assert.match(measurementMappingGuidance("resolved"), /not medical certainty/);
assert.equal(resolveBiomarkerPanelMode({ extractedCount: 0, observationCount: 3 }), "observations-fallback");
assert.equal(resolveBiomarkerReviewAction({ mode: "extracted-review", documentStatus: "needs_review", reviewableExtractedCount: 2 }), "accept-extracted");
assert.equal(reviewDataErrorMessage({ message: "query failed" }), "Biomarker review data could not be loaded.");
assert.deepEqual(validateObservationFallbackConfirmation({ documentStatus: "needs_review", submittedObservationIds: ["a"], linkedObservationIds: ["a"], reviewableExtractedCount: 0 }), { ok: true });
console.log("verify-document-review: all checks passed");
